// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: platform/v1/capabilities.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 自动驾驶系统类型。
type AutonomyStack int32

const (
	AutonomyStack_AUTONOMY_STACK_UNSPECIFIED   AutonomyStack = 0
	AutonomyStack_AUTONOMY_STACK_AUTOWARE_ROS2 AutonomyStack = 1
	AutonomyStack_AUTONOMY_STACK_GENERIC_ROS2  AutonomyStack = 2
	AutonomyStack_AUTONOMY_STACK_ROS1          AutonomyStack = 3 // 存量 ROS 1 车辆（过渡兼容）
	AutonomyStack_AUTONOMY_STACK_APOLLO_CYBER  AutonomyStack = 4
)

// Enum value maps for AutonomyStack.
var (
	AutonomyStack_name = map[int32]string{
		0: "AUTONOMY_STACK_UNSPECIFIED",
		1: "AUTONOMY_STACK_AUTOWARE_ROS2",
		2: "AUTONOMY_STACK_GENERIC_ROS2",
		3: "AUTONOMY_STACK_ROS1",
		4: "AUTONOMY_STACK_APOLLO_CYBER",
	}
	AutonomyStack_value = map[string]int32{
		"AUTONOMY_STACK_UNSPECIFIED":   0,
		"AUTONOMY_STACK_AUTOWARE_ROS2": 1,
		"AUTONOMY_STACK_GENERIC_ROS2":  2,
		"AUTONOMY_STACK_ROS1":          3,
		"AUTONOMY_STACK_APOLLO_CYBER":  4,
	}
)

func (x AutonomyStack) Enum() *AutonomyStack {
	p := new(AutonomyStack)
	*p = x
	return p
}

func (x AutonomyStack) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AutonomyStack) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_capabilities_proto_enumTypes[0].Descriptor()
}

func (AutonomyStack) Type() protoreflect.EnumType {
	return &file_platform_v1_capabilities_proto_enumTypes[0]
}

func (x AutonomyStack) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AutonomyStack.Descriptor instead.
func (AutonomyStack) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_capabilities_proto_rawDescGZIP(), []int{0}
}

// 相机能力。
type CameraCapability struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CameraId       string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Width          uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height         uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Fps            uint32                 `protobuf:"varint,4,opt,name=fps,proto3" json:"fps,omitempty"`
	Codec          string                 `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"` // 如 h264
	MaxBitrateKbps uint32                 `protobuf:"varint,6,opt,name=max_bitrate_kbps,json=maxBitrateKbps,proto3" json:"max_bitrate_kbps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CameraCapability) Reset() {
	*x = CameraCapability{}
	mi := &file_platform_v1_capabilities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraCapability) ProtoMessage() {}

func (x *CameraCapability) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_capabilities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraCapability.ProtoReflect.Descriptor instead.
func (*CameraCapability) Descriptor() ([]byte, []int) {
	return file_platform_v1_capabilities_proto_rawDescGZIP(), []int{0}
}

func (x *CameraCapability) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *CameraCapability) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CameraCapability) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CameraCapability) GetFps() uint32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *CameraCapability) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *CameraCapability) GetMaxBitrateKbps() uint32 {
	if x != nil {
		return x.MaxBitrateKbps
	}
	return 0
}

// Modem/运营商信息（双链路要求两个不同运营商的独立 Modem；
// 双 SIM 共用一张网卡不构成真正冗余）。
type ModemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModemId       string                 `protobuf:"bytes,1,opt,name=modem_id,json=modemId,proto3" json:"modem_id,omitempty"`
	Carrier       string                 `protobuf:"bytes,2,opt,name=carrier,proto3" json:"carrier,omitempty"`
	Iccid         string                 `protobuf:"bytes,3,opt,name=iccid,proto3" json:"iccid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModemInfo) Reset() {
	*x = ModemInfo{}
	mi := &file_platform_v1_capabilities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModemInfo) ProtoMessage() {}

func (x *ModemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_capabilities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModemInfo.ProtoReflect.Descriptor instead.
func (*ModemInfo) Descriptor() ([]byte, []int) {
	return file_platform_v1_capabilities_proto_rawDescGZIP(), []int{1}
}

func (x *ModemInfo) GetModemId() string {
	if x != nil {
		return x.ModemId
	}
	return ""
}

func (x *ModemInfo) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *ModemInfo) GetIccid() string {
	if x != nil {
		return x.Iccid
	}
	return ""
}

// 地图能力。
type MapCapability struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MapFormats      []string               `protobuf:"bytes,1,rep,name=map_formats,json=mapFormats,proto3" json:"map_formats,omitempty"`                // pcd / lanelet2_osm / apollo_map / opendrive
	CoordinateFrame string                 `protobuf:"bytes,2,opt,name=coordinate_frame,json=coordinateFrame,proto3" json:"coordinate_frame,omitempty"` // 坐标系标识，如 EPSG:xxxx
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MapCapability) Reset() {
	*x = MapCapability{}
	mi := &file_platform_v1_capabilities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapCapability) ProtoMessage() {}

func (x *MapCapability) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_capabilities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapCapability.ProtoReflect.Descriptor instead.
func (*MapCapability) Descriptor() ([]byte, []int) {
	return file_platform_v1_capabilities_proto_rawDescGZIP(), []int{2}
}

func (x *MapCapability) GetMapFormats() []string {
	if x != nil {
		return x.MapFormats
	}
	return nil
}

func (x *MapCapability) GetCoordinateFrame() string {
	if x != nil {
		return x.CoordinateFrame
	}
	return ""
}

// Gateway 能力声明。
type GatewayCapabilities struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleId      string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	GatewayVersion string                 `protobuf:"bytes,2,opt,name=gateway_version,json=gatewayVersion,proto3" json:"gateway_version,omitempty"`
	// 自动驾驶系统及版本（含存量 ROS 1 及发行版）。
	Stack        AutonomyStack `protobuf:"varint,3,opt,name=stack,proto3,enum=platform.v1.AutonomyStack" json:"stack,omitempty"`
	StackVersion string        `protobuf:"bytes,4,opt,name=stack_version,json=stackVersion,proto3" json:"stack_version,omitempty"` // 如 "ROS 1 Noetic" / "Autoware v0.x"
	// 支持的控制模式（接管前必须返回当前可用模式）。
	SupportedControlModes []ControlMode `protobuf:"varint,5,rep,packed,name=supported_control_modes,json=supportedControlModes,proto3,enum=platform.v1.ControlMode" json:"supported_control_modes,omitempty"`
	// ROS 2 Topic / ROS 1 Topic / Cyber Channel 映射版本。
	TopicMappingVersion string              `protobuf:"bytes,6,opt,name=topic_mapping_version,json=topicMappingVersion,proto3" json:"topic_mapping_version,omitempty"`
	Cameras             []*CameraCapability `protobuf:"bytes,7,rep,name=cameras,proto3" json:"cameras,omitempty"`
	Modems              []*ModemInfo        `protobuf:"bytes,8,rep,name=modems,proto3" json:"modems,omitempty"`
	// 安全能力。
	TpmAvailable         bool `protobuf:"varint,9,opt,name=tpm_available,json=tpmAvailable,proto3" json:"tpm_available,omitempty"`
	CertificateInstalled bool `protobuf:"varint,10,opt,name=certificate_installed,json=certificateInstalled,proto3" json:"certificate_installed,omitempty"`
	// 维护能力：vpn / ssh / sovd / uds_doip / gui。
	WorkspaceFeatures    []string       `protobuf:"bytes,11,rep,name=workspace_features,json=workspaceFeatures,proto3" json:"workspace_features,omitempty"`
	Map                  *MapCapability `protobuf:"bytes,12,opt,name=map,proto3" json:"map,omitempty"`
	AdapterVersion       string         `protobuf:"bytes,13,opt,name=adapter_version,json=adapterVersion,proto3" json:"adapter_version,omitempty"`
	SafetyArbiterVersion string         `protobuf:"bytes,14,opt,name=safety_arbiter_version,json=safetyArbiterVersion,proto3" json:"safety_arbiter_version,omitempty"`
	// 车辆侧已审核的底盘/项目归属，不由云端根据固定车辆推断。
	ChassisType   string `protobuf:"bytes,15,opt,name=chassis_type,json=chassisType,proto3" json:"chassis_type,omitempty"`
	GroupId       string `protobuf:"bytes,16,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayCapabilities) Reset() {
	*x = GatewayCapabilities{}
	mi := &file_platform_v1_capabilities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCapabilities) ProtoMessage() {}

func (x *GatewayCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_capabilities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCapabilities.ProtoReflect.Descriptor instead.
func (*GatewayCapabilities) Descriptor() ([]byte, []int) {
	return file_platform_v1_capabilities_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayCapabilities) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *GatewayCapabilities) GetGatewayVersion() string {
	if x != nil {
		return x.GatewayVersion
	}
	return ""
}

func (x *GatewayCapabilities) GetStack() AutonomyStack {
	if x != nil {
		return x.Stack
	}
	return AutonomyStack_AUTONOMY_STACK_UNSPECIFIED
}

func (x *GatewayCapabilities) GetStackVersion() string {
	if x != nil {
		return x.StackVersion
	}
	return ""
}

func (x *GatewayCapabilities) GetSupportedControlModes() []ControlMode {
	if x != nil {
		return x.SupportedControlModes
	}
	return nil
}

func (x *GatewayCapabilities) GetTopicMappingVersion() string {
	if x != nil {
		return x.TopicMappingVersion
	}
	return ""
}

func (x *GatewayCapabilities) GetCameras() []*CameraCapability {
	if x != nil {
		return x.Cameras
	}
	return nil
}

func (x *GatewayCapabilities) GetModems() []*ModemInfo {
	if x != nil {
		return x.Modems
	}
	return nil
}

func (x *GatewayCapabilities) GetTpmAvailable() bool {
	if x != nil {
		return x.TpmAvailable
	}
	return false
}

func (x *GatewayCapabilities) GetCertificateInstalled() bool {
	if x != nil {
		return x.CertificateInstalled
	}
	return false
}

func (x *GatewayCapabilities) GetWorkspaceFeatures() []string {
	if x != nil {
		return x.WorkspaceFeatures
	}
	return nil
}

func (x *GatewayCapabilities) GetMap() *MapCapability {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *GatewayCapabilities) GetAdapterVersion() string {
	if x != nil {
		return x.AdapterVersion
	}
	return ""
}

func (x *GatewayCapabilities) GetSafetyArbiterVersion() string {
	if x != nil {
		return x.SafetyArbiterVersion
	}
	return ""
}

func (x *GatewayCapabilities) GetChassisType() string {
	if x != nil {
		return x.ChassisType
	}
	return ""
}

func (x *GatewayCapabilities) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

var File_platform_v1_capabilities_proto protoreflect.FileDescriptor

const file_platform_v1_capabilities_proto_rawDesc = "" +
	"\n" +
	"\x1eplatform/v1/capabilities.proto\x12\vplatform.v1\x1a\x19platform/v1/control.proto\"\xaf\x01\n" +
	"\x10CameraCapability\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12\x10\n" +
	"\x03fps\x18\x04 \x01(\rR\x03fps\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\tR\x05codec\x12(\n" +
	"\x10max_bitrate_kbps\x18\x06 \x01(\rR\x0emaxBitrateKbps\"V\n" +
	"\tModemInfo\x12\x19\n" +
	"\bmodem_id\x18\x01 \x01(\tR\amodemId\x12\x18\n" +
	"\acarrier\x18\x02 \x01(\tR\acarrier\x12\x14\n" +
	"\x05iccid\x18\x03 \x01(\tR\x05iccid\"[\n" +
	"\rMapCapability\x12\x1f\n" +
	"\vmap_formats\x18\x01 \x03(\tR\n" +
	"mapFormats\x12)\n" +
	"\x10coordinate_frame\x18\x02 \x01(\tR\x0fcoordinateFrame\"\xf7\x05\n" +
	"\x13GatewayCapabilities\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12'\n" +
	"\x0fgateway_version\x18\x02 \x01(\tR\x0egatewayVersion\x120\n" +
	"\x05stack\x18\x03 \x01(\x0e2\x1a.platform.v1.AutonomyStackR\x05stack\x12#\n" +
	"\rstack_version\x18\x04 \x01(\tR\fstackVersion\x12P\n" +
	"\x17supported_control_modes\x18\x05 \x03(\x0e2\x18.platform.v1.ControlModeR\x15supportedControlModes\x122\n" +
	"\x15topic_mapping_version\x18\x06 \x01(\tR\x13topicMappingVersion\x127\n" +
	"\acameras\x18\a \x03(\v2\x1d.platform.v1.CameraCapabilityR\acameras\x12.\n" +
	"\x06modems\x18\b \x03(\v2\x16.platform.v1.ModemInfoR\x06modems\x12#\n" +
	"\rtpm_available\x18\t \x01(\bR\ftpmAvailable\x123\n" +
	"\x15certificate_installed\x18\n" +
	" \x01(\bR\x14certificateInstalled\x12-\n" +
	"\x12workspace_features\x18\v \x03(\tR\x11workspaceFeatures\x12,\n" +
	"\x03map\x18\f \x01(\v2\x1a.platform.v1.MapCapabilityR\x03map\x12'\n" +
	"\x0fadapter_version\x18\r \x01(\tR\x0eadapterVersion\x124\n" +
	"\x16safety_arbiter_version\x18\x0e \x01(\tR\x14safetyArbiterVersion\x12!\n" +
	"\fchassis_type\x18\x0f \x01(\tR\vchassisType\x12\x19\n" +
	"\bgroup_id\x18\x10 \x01(\tR\agroupId*\xac\x01\n" +
	"\rAutonomyStack\x12\x1e\n" +
	"\x1aAUTONOMY_STACK_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cAUTONOMY_STACK_AUTOWARE_ROS2\x10\x01\x12\x1f\n" +
	"\x1bAUTONOMY_STACK_GENERIC_ROS2\x10\x02\x12\x17\n" +
	"\x13AUTONOMY_STACK_ROS1\x10\x03\x12\x1f\n" +
	"\x1bAUTONOMY_STACK_APOLLO_CYBER\x10\x04B.Z,robot-agent/protocols/platform/v1;platformv1b\x06proto3"

var (
	file_platform_v1_capabilities_proto_rawDescOnce sync.Once
	file_platform_v1_capabilities_proto_rawDescData []byte
)

func file_platform_v1_capabilities_proto_rawDescGZIP() []byte {
	file_platform_v1_capabilities_proto_rawDescOnce.Do(func() {
		file_platform_v1_capabilities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_capabilities_proto_rawDesc), len(file_platform_v1_capabilities_proto_rawDesc)))
	})
	return file_platform_v1_capabilities_proto_rawDescData
}

var file_platform_v1_capabilities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platform_v1_capabilities_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_platform_v1_capabilities_proto_goTypes = []any{
	(AutonomyStack)(0),          // 0: platform.v1.AutonomyStack
	(*CameraCapability)(nil),    // 1: platform.v1.CameraCapability
	(*ModemInfo)(nil),           // 2: platform.v1.ModemInfo
	(*MapCapability)(nil),       // 3: platform.v1.MapCapability
	(*GatewayCapabilities)(nil), // 4: platform.v1.GatewayCapabilities
	(ControlMode)(0),            // 5: platform.v1.ControlMode
}
var file_platform_v1_capabilities_proto_depIdxs = []int32{
	0, // 0: platform.v1.GatewayCapabilities.stack:type_name -> platform.v1.AutonomyStack
	5, // 1: platform.v1.GatewayCapabilities.supported_control_modes:type_name -> platform.v1.ControlMode
	1, // 2: platform.v1.GatewayCapabilities.cameras:type_name -> platform.v1.CameraCapability
	2, // 3: platform.v1.GatewayCapabilities.modems:type_name -> platform.v1.ModemInfo
	3, // 4: platform.v1.GatewayCapabilities.map:type_name -> platform.v1.MapCapability
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_platform_v1_capabilities_proto_init() }
func file_platform_v1_capabilities_proto_init() {
	if File_platform_v1_capabilities_proto != nil {
		return
	}
	file_platform_v1_control_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_capabilities_proto_rawDesc), len(file_platform_v1_capabilities_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_capabilities_proto_goTypes,
		DependencyIndexes: file_platform_v1_capabilities_proto_depIdxs,
		EnumInfos:         file_platform_v1_capabilities_proto_enumTypes,
		MessageInfos:      file_platform_v1_capabilities_proto_msgTypes,
	}.Build()
	File_platform_v1_capabilities_proto = out.File
	file_platform_v1_capabilities_proto_goTypes = nil
	file_platform_v1_capabilities_proto_depIdxs = nil
}
