// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: platform/v1/control.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 控制模式。
type ControlMode int32

const (
	ControlMode_CONTROL_MODE_UNSPECIFIED      ControlMode = 0
	ControlMode_CONTROL_MODE_DIRECT_ACTUATION ControlMode = 1 // 直接执行器：转向/油门/制动/挡位（限定低速区域）
	ControlMode_CONTROL_MODE_TARGET_MOTION    ControlMode = 2 // 目标运动：速度/加速度/曲率/横摆率（车端本地闭环优先）
	ControlMode_CONTROL_MODE_TRAJECTORY       ControlMode = 3 // 轨迹：带时间戳轨迹点（远程辅助优先）
	ControlMode_CONTROL_MODE_MINIMAL_RISK     ControlMode = 4 // 最小风险：车端执行安全停车等策略
)

// Enum value maps for ControlMode.
var (
	ControlMode_name = map[int32]string{
		0: "CONTROL_MODE_UNSPECIFIED",
		1: "CONTROL_MODE_DIRECT_ACTUATION",
		2: "CONTROL_MODE_TARGET_MOTION",
		3: "CONTROL_MODE_TRAJECTORY",
		4: "CONTROL_MODE_MINIMAL_RISK",
	}
	ControlMode_value = map[string]int32{
		"CONTROL_MODE_UNSPECIFIED":      0,
		"CONTROL_MODE_DIRECT_ACTUATION": 1,
		"CONTROL_MODE_TARGET_MOTION":    2,
		"CONTROL_MODE_TRAJECTORY":       3,
		"CONTROL_MODE_MINIMAL_RISK":     4,
	}
)

func (x ControlMode) Enum() *ControlMode {
	p := new(ControlMode)
	*p = x
	return p
}

func (x ControlMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlMode) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_control_proto_enumTypes[0].Descriptor()
}

func (ControlMode) Type() protoreflect.EnumType {
	return &file_platform_v1_control_proto_enumTypes[0]
}

func (x ControlMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlMode.Descriptor instead.
func (ControlMode) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{0}
}

// 挡位。
type Gear int32

const (
	Gear_GEAR_UNSPECIFIED Gear = 0
	Gear_GEAR_PARK        Gear = 1
	Gear_GEAR_REVERSE     Gear = 2
	Gear_GEAR_NEUTRAL     Gear = 3
	Gear_GEAR_DRIVE       Gear = 4
)

// Enum value maps for Gear.
var (
	Gear_name = map[int32]string{
		0: "GEAR_UNSPECIFIED",
		1: "GEAR_PARK",
		2: "GEAR_REVERSE",
		3: "GEAR_NEUTRAL",
		4: "GEAR_DRIVE",
	}
	Gear_value = map[string]int32{
		"GEAR_UNSPECIFIED": 0,
		"GEAR_PARK":        1,
		"GEAR_REVERSE":     2,
		"GEAR_NEUTRAL":     3,
		"GEAR_DRIVE":       4,
	}
)

func (x Gear) Enum() *Gear {
	p := new(Gear)
	*p = x
	return p
}

func (x Gear) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gear) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_control_proto_enumTypes[1].Descriptor()
}

func (Gear) Type() protoreflect.EnumType {
	return &file_platform_v1_control_proto_enumTypes[1]
}

func (x Gear) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gear.Descriptor instead.
func (Gear) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{1}
}

// 最小风险触发原因。
type MinimalRiskReason int32

const (
	MinimalRiskReason_MINIMAL_RISK_REASON_UNSPECIFIED    MinimalRiskReason = 0
	MinimalRiskReason_MINIMAL_RISK_REASON_LINK_LOSS      MinimalRiskReason = 1 // 双链路均丢失
	MinimalRiskReason_MINIMAL_RISK_REASON_LEASE_EXPIRED  MinimalRiskReason = 2 // 控制权租约到期
	MinimalRiskReason_MINIMAL_RISK_REASON_DRIVER_REQUEST MinimalRiskReason = 3
	MinimalRiskReason_MINIMAL_RISK_REASON_SYSTEM_FAULT   MinimalRiskReason = 4
)

// Enum value maps for MinimalRiskReason.
var (
	MinimalRiskReason_name = map[int32]string{
		0: "MINIMAL_RISK_REASON_UNSPECIFIED",
		1: "MINIMAL_RISK_REASON_LINK_LOSS",
		2: "MINIMAL_RISK_REASON_LEASE_EXPIRED",
		3: "MINIMAL_RISK_REASON_DRIVER_REQUEST",
		4: "MINIMAL_RISK_REASON_SYSTEM_FAULT",
	}
	MinimalRiskReason_value = map[string]int32{
		"MINIMAL_RISK_REASON_UNSPECIFIED":    0,
		"MINIMAL_RISK_REASON_LINK_LOSS":      1,
		"MINIMAL_RISK_REASON_LEASE_EXPIRED":  2,
		"MINIMAL_RISK_REASON_DRIVER_REQUEST": 3,
		"MINIMAL_RISK_REASON_SYSTEM_FAULT":   4,
	}
)

func (x MinimalRiskReason) Enum() *MinimalRiskReason {
	p := new(MinimalRiskReason)
	*p = x
	return p
}

func (x MinimalRiskReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MinimalRiskReason) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_control_proto_enumTypes[2].Descriptor()
}

func (MinimalRiskReason) Type() protoreflect.EnumType {
	return &file_platform_v1_control_proto_enumTypes[2]
}

func (x MinimalRiskReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MinimalRiskReason.Descriptor instead.
func (MinimalRiskReason) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{2}
}

// 车端校验/执行结果。
type ControlResult int32

const (
	ControlResult_CONTROL_RESULT_UNSPECIFIED      ControlResult = 0
	ControlResult_CONTROL_RESULT_ACCEPTED         ControlResult = 1
	ControlResult_CONTROL_RESULT_REJECTED_STALE   ControlResult = 2 // 过期（TTL/序号落后）
	ControlResult_CONTROL_RESULT_REJECTED_FENCING ControlResult = 3 // fencing token 无效
	ControlResult_CONTROL_RESULT_REJECTED_LEASE   ControlResult = 4 // 租约无效
	ControlResult_CONTROL_RESULT_REJECTED_LIMIT   ControlResult = 5 // 超出安全限幅
	ControlResult_CONTROL_RESULT_FAILED           ControlResult = 6 // 执行失败
)

// Enum value maps for ControlResult.
var (
	ControlResult_name = map[int32]string{
		0: "CONTROL_RESULT_UNSPECIFIED",
		1: "CONTROL_RESULT_ACCEPTED",
		2: "CONTROL_RESULT_REJECTED_STALE",
		3: "CONTROL_RESULT_REJECTED_FENCING",
		4: "CONTROL_RESULT_REJECTED_LEASE",
		5: "CONTROL_RESULT_REJECTED_LIMIT",
		6: "CONTROL_RESULT_FAILED",
	}
	ControlResult_value = map[string]int32{
		"CONTROL_RESULT_UNSPECIFIED":      0,
		"CONTROL_RESULT_ACCEPTED":         1,
		"CONTROL_RESULT_REJECTED_STALE":   2,
		"CONTROL_RESULT_REJECTED_FENCING": 3,
		"CONTROL_RESULT_REJECTED_LEASE":   4,
		"CONTROL_RESULT_REJECTED_LIMIT":   5,
		"CONTROL_RESULT_FAILED":           6,
	}
)

func (x ControlResult) Enum() *ControlResult {
	p := new(ControlResult)
	*p = x
	return p
}

func (x ControlResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlResult) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_control_proto_enumTypes[3].Descriptor()
}

func (ControlResult) Type() protoreflect.EnumType {
	return &file_platform_v1_control_proto_enumTypes[3]
}

func (x ControlResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlResult.Descriptor instead.
func (ControlResult) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{3}
}

// Authority 对车端下发的控制权状态。签名覆盖除 authority_signature
// 之外的全部字段，车端 Arbiter 只接受已配置的 Authority 公钥。
type LeaseAction int32

const (
	LeaseAction_LEASE_ACTION_UNSPECIFIED LeaseAction = 0
	LeaseAction_LEASE_ACTION_GRANT       LeaseAction = 1
	LeaseAction_LEASE_ACTION_REVOKE      LeaseAction = 2
)

// Enum value maps for LeaseAction.
var (
	LeaseAction_name = map[int32]string{
		0: "LEASE_ACTION_UNSPECIFIED",
		1: "LEASE_ACTION_GRANT",
		2: "LEASE_ACTION_REVOKE",
	}
	LeaseAction_value = map[string]int32{
		"LEASE_ACTION_UNSPECIFIED": 0,
		"LEASE_ACTION_GRANT":       1,
		"LEASE_ACTION_REVOKE":      2,
	}
)

func (x LeaseAction) Enum() *LeaseAction {
	p := new(LeaseAction)
	*p = x
	return p
}

func (x LeaseAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaseAction) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_control_proto_enumTypes[4].Descriptor()
}

func (LeaseAction) Type() protoreflect.EnumType {
	return &file_platform_v1_control_proto_enumTypes[4]
}

func (x LeaseAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaseAction.Descriptor instead.
func (LeaseAction) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{4}
}

// 直接执行器指令。单位一律 SI；油门/制动为 0..1 比例，
// 由车端 Adapter 按车辆能力清单和标定文件转换，云端不做假设。
type DirectActuation struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SteeringAngleTargetRad float64                `protobuf:"fixed64,1,opt,name=steering_angle_target_rad,json=steeringAngleTargetRad,proto3" json:"steering_angle_target_rad,omitempty"` // 目标方向盘转角（弧度）
	ThrottleFraction       float64                `protobuf:"fixed64,2,opt,name=throttle_fraction,json=throttleFraction,proto3" json:"throttle_fraction,omitempty"`                       // 0..1
	BrakeFraction          float64                `protobuf:"fixed64,3,opt,name=brake_fraction,json=brakeFraction,proto3" json:"brake_fraction,omitempty"`                                // 0..1
	Gear                   Gear                   `protobuf:"varint,4,opt,name=gear,proto3,enum=platform.v1.Gear" json:"gear,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DirectActuation) Reset() {
	*x = DirectActuation{}
	mi := &file_platform_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectActuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectActuation) ProtoMessage() {}

func (x *DirectActuation) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectActuation.ProtoReflect.Descriptor instead.
func (*DirectActuation) Descriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *DirectActuation) GetSteeringAngleTargetRad() float64 {
	if x != nil {
		return x.SteeringAngleTargetRad
	}
	return 0
}

func (x *DirectActuation) GetThrottleFraction() float64 {
	if x != nil {
		return x.ThrottleFraction
	}
	return 0
}

func (x *DirectActuation) GetBrakeFraction() float64 {
	if x != nil {
		return x.BrakeFraction
	}
	return 0
}

func (x *DirectActuation) GetGear() Gear {
	if x != nil {
		return x.Gear
	}
	return Gear_GEAR_UNSPECIFIED
}

// 目标运动指令。
type TargetMotion struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TargetSpeedMps         float64                `protobuf:"fixed64,1,opt,name=target_speed_mps,json=targetSpeedMps,proto3" json:"target_speed_mps,omitempty"`                         // m/s
	TargetAccelerationMps2 float64                `protobuf:"fixed64,2,opt,name=target_acceleration_mps2,json=targetAccelerationMps2,proto3" json:"target_acceleration_mps2,omitempty"` // m/s^2
	TargetCurvatureInvM    float64                `protobuf:"fixed64,3,opt,name=target_curvature_inv_m,json=targetCurvatureInvM,proto3" json:"target_curvature_inv_m,omitempty"`        // 1/m
	TargetYawRateRadps     float64                `protobuf:"fixed64,4,opt,name=target_yaw_rate_radps,json=targetYawRateRadps,proto3" json:"target_yaw_rate_radps,omitempty"`           // rad/s
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TargetMotion) Reset() {
	*x = TargetMotion{}
	mi := &file_platform_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetMotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetMotion) ProtoMessage() {}

func (x *TargetMotion) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetMotion.ProtoReflect.Descriptor instead.
func (*TargetMotion) Descriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *TargetMotion) GetTargetSpeedMps() float64 {
	if x != nil {
		return x.TargetSpeedMps
	}
	return 0
}

func (x *TargetMotion) GetTargetAccelerationMps2() float64 {
	if x != nil {
		return x.TargetAccelerationMps2
	}
	return 0
}

func (x *TargetMotion) GetTargetCurvatureInvM() float64 {
	if x != nil {
		return x.TargetCurvatureInvM
	}
	return 0
}

func (x *TargetMotion) GetTargetYawRateRadps() float64 {
	if x != nil {
		return x.TargetYawRateRadps
	}
	return 0
}

// 轨迹点。
type TrajectoryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XM            float64                `protobuf:"fixed64,1,opt,name=x_m,json=xM,proto3" json:"x_m,omitempty"`
	YM            float64                `protobuf:"fixed64,2,opt,name=y_m,json=yM,proto3" json:"y_m,omitempty"`
	HeadingRad    float64                `protobuf:"fixed64,3,opt,name=heading_rad,json=headingRad,proto3" json:"heading_rad,omitempty"`
	SpeedMps      float64                `protobuf:"fixed64,4,opt,name=speed_mps,json=speedMps,proto3" json:"speed_mps,omitempty"`
	TimeOffsetS   float64                `protobuf:"fixed64,5,opt,name=time_offset_s,json=timeOffsetS,proto3" json:"time_offset_s,omitempty"` // 相对命令下发时刻
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrajectoryPoint) Reset() {
	*x = TrajectoryPoint{}
	mi := &file_platform_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrajectoryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrajectoryPoint) ProtoMessage() {}

func (x *TrajectoryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrajectoryPoint.ProtoReflect.Descriptor instead.
func (*TrajectoryPoint) Descriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *TrajectoryPoint) GetXM() float64 {
	if x != nil {
		return x.XM
	}
	return 0
}

func (x *TrajectoryPoint) GetYM() float64 {
	if x != nil {
		return x.YM
	}
	return 0
}

func (x *TrajectoryPoint) GetHeadingRad() float64 {
	if x != nil {
		return x.HeadingRad
	}
	return 0
}

func (x *TrajectoryPoint) GetSpeedMps() float64 {
	if x != nil {
		return x.SpeedMps
	}
	return 0
}

func (x *TrajectoryPoint) GetTimeOffsetS() float64 {
	if x != nil {
		return x.TimeOffsetS
	}
	return 0
}

// 轨迹指令。
type Trajectory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TrajectoryPoint     `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trajectory) Reset() {
	*x = Trajectory{}
	mi := &file_platform_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trajectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trajectory) ProtoMessage() {}

func (x *Trajectory) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trajectory.ProtoReflect.Descriptor instead.
func (*Trajectory) Descriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *Trajectory) GetPoints() []*TrajectoryPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// 最小风险指令：车端按本地策略执行（如安全停车）。
type MinimalRiskCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        MinimalRiskReason      `protobuf:"varint,1,opt,name=reason,proto3,enum=platform.v1.MinimalRiskReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinimalRiskCommand) Reset() {
	*x = MinimalRiskCommand{}
	mi := &file_platform_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinimalRiskCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinimalRiskCommand) ProtoMessage() {}

func (x *MinimalRiskCommand) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinimalRiskCommand.ProtoReflect.Descriptor instead.
func (*MinimalRiskCommand) Descriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *MinimalRiskCommand) GetReason() MinimalRiskReason {
	if x != nil {
		return x.Reason
	}
	return MinimalRiskReason_MINIMAL_RISK_REASON_UNSPECIFIED
}

// 控制命令（双链路双发；车端按 fencing token + 序号 + TTL 校验去重）。
type ControlCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ControlSessionId  string                 `protobuf:"bytes,1,opt,name=control_session_id,json=controlSessionId,proto3" json:"control_session_id,omitempty"`
	LeaseId           string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	FencingToken      uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	CommandSequence   uint64                 `protobuf:"varint,4,opt,name=command_sequence,json=commandSequence,proto3" json:"command_sequence,omitempty"`
	IssuedMonotonicNs uint64                 `protobuf:"varint,5,opt,name=issued_monotonic_ns,json=issuedMonotonicNs,proto3" json:"issued_monotonic_ns,omitempty"`
	TtlMs             uint32                 `protobuf:"varint,6,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"` // 到期即弃，不执行旧命令
	Mode              ControlMode            `protobuf:"varint,7,opt,name=mode,proto3,enum=platform.v1.ControlMode" json:"mode,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*ControlCommand_Direct
	//	*ControlCommand_Motion
	//	*ControlCommand_Trajectory
	//	*ControlCommand_MinimalRisk
	Command isControlCommand_Command `protobuf_oneof:"command"`
	// 端到端完整性校验。
	EndToEndMac   []byte `protobuf:"bytes,20,opt,name=end_to_end_mac,json=endToEndMac,proto3" json:"end_to_end_mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlCommand) Reset() {
	*x = ControlCommand{}
	mi := &file_platform_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCommand) ProtoMessage() {}

func (x *ControlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCommand.ProtoReflect.Descriptor instead.
func (*ControlCommand) Descriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ControlCommand) GetControlSessionId() string {
	if x != nil {
		return x.ControlSessionId
	}
	return ""
}

func (x *ControlCommand) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ControlCommand) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *ControlCommand) GetCommandSequence() uint64 {
	if x != nil {
		return x.CommandSequence
	}
	return 0
}

func (x *ControlCommand) GetIssuedMonotonicNs() uint64 {
	if x != nil {
		return x.IssuedMonotonicNs
	}
	return 0
}

func (x *ControlCommand) GetTtlMs() uint32 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *ControlCommand) GetMode() ControlMode {
	if x != nil {
		return x.Mode
	}
	return ControlMode_CONTROL_MODE_UNSPECIFIED
}

func (x *ControlCommand) GetCommand() isControlCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ControlCommand) GetDirect() *DirectActuation {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Direct); ok {
			return x.Direct
		}
	}
	return nil
}

func (x *ControlCommand) GetMotion() *TargetMotion {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Motion); ok {
			return x.Motion
		}
	}
	return nil
}

func (x *ControlCommand) GetTrajectory() *Trajectory {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Trajectory); ok {
			return x.Trajectory
		}
	}
	return nil
}

func (x *ControlCommand) GetMinimalRisk() *MinimalRiskCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_MinimalRisk); ok {
			return x.MinimalRisk
		}
	}
	return nil
}

func (x *ControlCommand) GetEndToEndMac() []byte {
	if x != nil {
		return x.EndToEndMac
	}
	return nil
}

type isControlCommand_Command interface {
	isControlCommand_Command()
}

type ControlCommand_Direct struct {
	Direct *DirectActuation `protobuf:"bytes,10,opt,name=direct,proto3,oneof"`
}

type ControlCommand_Motion struct {
	Motion *TargetMotion `protobuf:"bytes,11,opt,name=motion,proto3,oneof"`
}

type ControlCommand_Trajectory struct {
	Trajectory *Trajectory `protobuf:"bytes,12,opt,name=trajectory,proto3,oneof"`
}

type ControlCommand_MinimalRisk struct {
	MinimalRisk *MinimalRiskCommand `protobuf:"bytes,13,opt,name=minimal_risk,json=minimalRisk,proto3,oneof"`
}

func (*ControlCommand_Direct) isControlCommand_Command() {}

func (*ControlCommand_Motion) isControlCommand_Command() {}

func (*ControlCommand_Trajectory) isControlCommand_Command() {}

func (*ControlCommand_MinimalRisk) isControlCommand_Command() {}

// 控制回执（审计与闭环测量用）。
type ControlAck struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ControlSessionId   string                 `protobuf:"bytes,1,opt,name=control_session_id,json=controlSessionId,proto3" json:"control_session_id,omitempty"`
	CommandSequence    uint64                 `protobuf:"varint,2,opt,name=command_sequence,json=commandSequence,proto3" json:"command_sequence,omitempty"`
	Result             ControlResult          `protobuf:"varint,3,opt,name=result,proto3,enum=platform.v1.ControlResult" json:"result,omitempty"`
	Detail             string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	AppliedMonotonicNs uint64                 `protobuf:"varint,5,opt,name=applied_monotonic_ns,json=appliedMonotonicNs,proto3" json:"applied_monotonic_ns,omitempty"` // 实际执行时刻，用于测量输入→执行延迟
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ControlAck) Reset() {
	*x = ControlAck{}
	mi := &file_platform_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlAck) ProtoMessage() {}

func (x *ControlAck) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlAck.ProtoReflect.Descriptor instead.
func (*ControlAck) Descriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *ControlAck) GetControlSessionId() string {
	if x != nil {
		return x.ControlSessionId
	}
	return ""
}

func (x *ControlAck) GetCommandSequence() uint64 {
	if x != nil {
		return x.CommandSequence
	}
	return 0
}

func (x *ControlAck) GetResult() ControlResult {
	if x != nil {
		return x.Result
	}
	return ControlResult_CONTROL_RESULT_UNSPECIFIED
}

func (x *ControlAck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ControlAck) GetAppliedMonotonicNs() uint64 {
	if x != nil {
		return x.AppliedMonotonicNs
	}
	return 0
}

type LeaseGrant struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Action             LeaseAction            `protobuf:"varint,2,opt,name=action,proto3,enum=platform.v1.LeaseAction" json:"action,omitempty"`
	VehicleId          string                 `protobuf:"bytes,3,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	GatewayId          string                 `protobuf:"bytes,4,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	LeaseId            string                 `protobuf:"bytes,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	DriverId           string                 `protobuf:"bytes,6,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DeviceId           string                 `protobuf:"bytes,7,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	FencingToken       uint64                 `protobuf:"varint,8,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	ValidUntilUnixNs   int64                  `protobuf:"varint,9,opt,name=valid_until_unix_ns,json=validUntilUnixNs,proto3" json:"valid_until_unix_ns,omitempty"`
	IssuedAtUnixNs     int64                  `protobuf:"varint,10,opt,name=issued_at_unix_ns,json=issuedAtUnixNs,proto3" json:"issued_at_unix_ns,omitempty"`
	AuthorityKeyId     string                 `protobuf:"bytes,11,opt,name=authority_key_id,json=authorityKeyId,proto3" json:"authority_key_id,omitempty"`
	AuthoritySignature []byte                 `protobuf:"bytes,12,opt,name=authority_signature,json=authoritySignature,proto3" json:"authority_signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LeaseGrant) Reset() {
	*x = LeaseGrant{}
	mi := &file_platform_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseGrant) ProtoMessage() {}

func (x *LeaseGrant) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseGrant.ProtoReflect.Descriptor instead.
func (*LeaseGrant) Descriptor() ([]byte, []int) {
	return file_platform_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *LeaseGrant) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LeaseGrant) GetAction() LeaseAction {
	if x != nil {
		return x.Action
	}
	return LeaseAction_LEASE_ACTION_UNSPECIFIED
}

func (x *LeaseGrant) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *LeaseGrant) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *LeaseGrant) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseGrant) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *LeaseGrant) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LeaseGrant) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LeaseGrant) GetValidUntilUnixNs() int64 {
	if x != nil {
		return x.ValidUntilUnixNs
	}
	return 0
}

func (x *LeaseGrant) GetIssuedAtUnixNs() int64 {
	if x != nil {
		return x.IssuedAtUnixNs
	}
	return 0
}

func (x *LeaseGrant) GetAuthorityKeyId() string {
	if x != nil {
		return x.AuthorityKeyId
	}
	return ""
}

func (x *LeaseGrant) GetAuthoritySignature() []byte {
	if x != nil {
		return x.AuthoritySignature
	}
	return nil
}

var File_platform_v1_control_proto protoreflect.FileDescriptor

const file_platform_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x19platform/v1/control.proto\x12\vplatform.v1\"\xc7\x01\n" +
	"\x0fDirectActuation\x129\n" +
	"\x19steering_angle_target_rad\x18\x01 \x01(\x01R\x16steeringAngleTargetRad\x12+\n" +
	"\x11throttle_fraction\x18\x02 \x01(\x01R\x10throttleFraction\x12%\n" +
	"\x0ebrake_fraction\x18\x03 \x01(\x01R\rbrakeFraction\x12%\n" +
	"\x04gear\x18\x04 \x01(\x0e2\x11.platform.v1.GearR\x04gear\"\xda\x01\n" +
	"\fTargetMotion\x12(\n" +
	"\x10target_speed_mps\x18\x01 \x01(\x01R\x0etargetSpeedMps\x128\n" +
	"\x18target_acceleration_mps2\x18\x02 \x01(\x01R\x16targetAccelerationMps2\x123\n" +
	"\x16target_curvature_inv_m\x18\x03 \x01(\x01R\x13targetCurvatureInvM\x121\n" +
	"\x15target_yaw_rate_radps\x18\x04 \x01(\x01R\x12targetYawRateRadps\"\x95\x01\n" +
	"\x0fTrajectoryPoint\x12\x0f\n" +
	"\x03x_m\x18\x01 \x01(\x01R\x02xM\x12\x0f\n" +
	"\x03y_m\x18\x02 \x01(\x01R\x02yM\x12\x1f\n" +
	"\vheading_rad\x18\x03 \x01(\x01R\n" +
	"headingRad\x12\x1b\n" +
	"\tspeed_mps\x18\x04 \x01(\x01R\bspeedMps\x12\"\n" +
	"\rtime_offset_s\x18\x05 \x01(\x01R\vtimeOffsetS\"B\n" +
	"\n" +
	"Trajectory\x124\n" +
	"\x06points\x18\x01 \x03(\v2\x1c.platform.v1.TrajectoryPointR\x06points\"L\n" +
	"\x12MinimalRiskCommand\x126\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1e.platform.v1.MinimalRiskReasonR\x06reason\"\xbc\x04\n" +
	"\x0eControlCommand\x12,\n" +
	"\x12control_session_id\x18\x01 \x01(\tR\x10controlSessionId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12)\n" +
	"\x10command_sequence\x18\x04 \x01(\x04R\x0fcommandSequence\x12.\n" +
	"\x13issued_monotonic_ns\x18\x05 \x01(\x04R\x11issuedMonotonicNs\x12\x15\n" +
	"\x06ttl_ms\x18\x06 \x01(\rR\x05ttlMs\x12,\n" +
	"\x04mode\x18\a \x01(\x0e2\x18.platform.v1.ControlModeR\x04mode\x126\n" +
	"\x06direct\x18\n" +
	" \x01(\v2\x1c.platform.v1.DirectActuationH\x00R\x06direct\x123\n" +
	"\x06motion\x18\v \x01(\v2\x19.platform.v1.TargetMotionH\x00R\x06motion\x129\n" +
	"\n" +
	"trajectory\x18\f \x01(\v2\x17.platform.v1.TrajectoryH\x00R\n" +
	"trajectory\x12D\n" +
	"\fminimal_risk\x18\r \x01(\v2\x1f.platform.v1.MinimalRiskCommandH\x00R\vminimalRisk\x12#\n" +
	"\x0eend_to_end_mac\x18\x14 \x01(\fR\vendToEndMacB\t\n" +
	"\acommand\"\xe3\x01\n" +
	"\n" +
	"ControlAck\x12,\n" +
	"\x12control_session_id\x18\x01 \x01(\tR\x10controlSessionId\x12)\n" +
	"\x10command_sequence\x18\x02 \x01(\x04R\x0fcommandSequence\x122\n" +
	"\x06result\x18\x03 \x01(\x0e2\x1a.platform.v1.ControlResultR\x06result\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x120\n" +
	"\x14applied_monotonic_ns\x18\x05 \x01(\x04R\x12appliedMonotonicNs\"\xc5\x03\n" +
	"\n" +
	"LeaseGrant\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x120\n" +
	"\x06action\x18\x02 \x01(\x0e2\x18.platform.v1.LeaseActionR\x06action\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x03 \x01(\tR\tvehicleId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x04 \x01(\tR\tgatewayId\x12\x19\n" +
	"\blease_id\x18\x05 \x01(\tR\aleaseId\x12\x1b\n" +
	"\tdriver_id\x18\x06 \x01(\tR\bdriverId\x12\x1b\n" +
	"\tdevice_id\x18\a \x01(\tR\bdeviceId\x12#\n" +
	"\rfencing_token\x18\b \x01(\x04R\ffencingToken\x12-\n" +
	"\x13valid_until_unix_ns\x18\t \x01(\x03R\x10validUntilUnixNs\x12)\n" +
	"\x11issued_at_unix_ns\x18\n" +
	" \x01(\x03R\x0eissuedAtUnixNs\x12(\n" +
	"\x10authority_key_id\x18\v \x01(\tR\x0eauthorityKeyId\x12/\n" +
	"\x13authority_signature\x18\f \x01(\fR\x12authoritySignature*\xaa\x01\n" +
	"\vControlMode\x12\x1c\n" +
	"\x18CONTROL_MODE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dCONTROL_MODE_DIRECT_ACTUATION\x10\x01\x12\x1e\n" +
	"\x1aCONTROL_MODE_TARGET_MOTION\x10\x02\x12\x1b\n" +
	"\x17CONTROL_MODE_TRAJECTORY\x10\x03\x12\x1d\n" +
	"\x19CONTROL_MODE_MINIMAL_RISK\x10\x04*_\n" +
	"\x04Gear\x12\x14\n" +
	"\x10GEAR_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tGEAR_PARK\x10\x01\x12\x10\n" +
	"\fGEAR_REVERSE\x10\x02\x12\x10\n" +
	"\fGEAR_NEUTRAL\x10\x03\x12\x0e\n" +
	"\n" +
	"GEAR_DRIVE\x10\x04*\xd0\x01\n" +
	"\x11MinimalRiskReason\x12#\n" +
	"\x1fMINIMAL_RISK_REASON_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dMINIMAL_RISK_REASON_LINK_LOSS\x10\x01\x12%\n" +
	"!MINIMAL_RISK_REASON_LEASE_EXPIRED\x10\x02\x12&\n" +
	"\"MINIMAL_RISK_REASON_DRIVER_REQUEST\x10\x03\x12$\n" +
	" MINIMAL_RISK_REASON_SYSTEM_FAULT\x10\x04*\xf5\x01\n" +
	"\rControlResult\x12\x1e\n" +
	"\x1aCONTROL_RESULT_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CONTROL_RESULT_ACCEPTED\x10\x01\x12!\n" +
	"\x1dCONTROL_RESULT_REJECTED_STALE\x10\x02\x12#\n" +
	"\x1fCONTROL_RESULT_REJECTED_FENCING\x10\x03\x12!\n" +
	"\x1dCONTROL_RESULT_REJECTED_LEASE\x10\x04\x12!\n" +
	"\x1dCONTROL_RESULT_REJECTED_LIMIT\x10\x05\x12\x19\n" +
	"\x15CONTROL_RESULT_FAILED\x10\x06*\\\n" +
	"\vLeaseAction\x12\x1c\n" +
	"\x18LEASE_ACTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12LEASE_ACTION_GRANT\x10\x01\x12\x17\n" +
	"\x13LEASE_ACTION_REVOKE\x10\x02B.Z,robot-agent/protocols/platform/v1;platformv1b\x06proto3"

var (
	file_platform_v1_control_proto_rawDescOnce sync.Once
	file_platform_v1_control_proto_rawDescData []byte
)

func file_platform_v1_control_proto_rawDescGZIP() []byte {
	file_platform_v1_control_proto_rawDescOnce.Do(func() {
		file_platform_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_control_proto_rawDesc), len(file_platform_v1_control_proto_rawDesc)))
	})
	return file_platform_v1_control_proto_rawDescData
}

var file_platform_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_platform_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_platform_v1_control_proto_goTypes = []any{
	(ControlMode)(0),           // 0: platform.v1.ControlMode
	(Gear)(0),                  // 1: platform.v1.Gear
	(MinimalRiskReason)(0),     // 2: platform.v1.MinimalRiskReason
	(ControlResult)(0),         // 3: platform.v1.ControlResult
	(LeaseAction)(0),           // 4: platform.v1.LeaseAction
	(*DirectActuation)(nil),    // 5: platform.v1.DirectActuation
	(*TargetMotion)(nil),       // 6: platform.v1.TargetMotion
	(*TrajectoryPoint)(nil),    // 7: platform.v1.TrajectoryPoint
	(*Trajectory)(nil),         // 8: platform.v1.Trajectory
	(*MinimalRiskCommand)(nil), // 9: platform.v1.MinimalRiskCommand
	(*ControlCommand)(nil),     // 10: platform.v1.ControlCommand
	(*ControlAck)(nil),         // 11: platform.v1.ControlAck
	(*LeaseGrant)(nil),         // 12: platform.v1.LeaseGrant
}
var file_platform_v1_control_proto_depIdxs = []int32{
	1,  // 0: platform.v1.DirectActuation.gear:type_name -> platform.v1.Gear
	7,  // 1: platform.v1.Trajectory.points:type_name -> platform.v1.TrajectoryPoint
	2,  // 2: platform.v1.MinimalRiskCommand.reason:type_name -> platform.v1.MinimalRiskReason
	0,  // 3: platform.v1.ControlCommand.mode:type_name -> platform.v1.ControlMode
	5,  // 4: platform.v1.ControlCommand.direct:type_name -> platform.v1.DirectActuation
	6,  // 5: platform.v1.ControlCommand.motion:type_name -> platform.v1.TargetMotion
	8,  // 6: platform.v1.ControlCommand.trajectory:type_name -> platform.v1.Trajectory
	9,  // 7: platform.v1.ControlCommand.minimal_risk:type_name -> platform.v1.MinimalRiskCommand
	3,  // 8: platform.v1.ControlAck.result:type_name -> platform.v1.ControlResult
	4,  // 9: platform.v1.LeaseGrant.action:type_name -> platform.v1.LeaseAction
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_platform_v1_control_proto_init() }
func file_platform_v1_control_proto_init() {
	if File_platform_v1_control_proto != nil {
		return
	}
	file_platform_v1_control_proto_msgTypes[5].OneofWrappers = []any{
		(*ControlCommand_Direct)(nil),
		(*ControlCommand_Motion)(nil),
		(*ControlCommand_Trajectory)(nil),
		(*ControlCommand_MinimalRisk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_control_proto_rawDesc), len(file_platform_v1_control_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_control_proto_goTypes,
		DependencyIndexes: file_platform_v1_control_proto_depIdxs,
		EnumInfos:         file_platform_v1_control_proto_enumTypes,
		MessageInfos:      file_platform_v1_control_proto_msgTypes,
	}.Build()
	File_platform_v1_control_proto = out.File
	file_platform_v1_control_proto_goTypes = nil
	file_platform_v1_control_proto_depIdxs = nil
}
