// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: platform/v1/envelope.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 统一消息信封：所有跨 车辆/云端/客户端 的消息都必须包在 Envelope 里。
// 对应架构文档 §6.1。
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 协议主版本：不兼容变更时增加；同一 major 内禁止复用字段编号。
	SchemaMajor uint32 `protobuf:"varint,1,opt,name=schema_major,json=schemaMajor,proto3" json:"schema_major,omitempty"`
	SchemaMinor uint32 `protobuf:"varint,2,opt,name=schema_minor,json=schemaMinor,proto3" json:"schema_minor,omitempty"`
	// payload 里消息的类型名，如 "platform.v1.SignalUpdate"。
	MessageType string `protobuf:"bytes,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	VehicleId   string `protobuf:"bytes,4,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	GatewayId   string `protobuf:"bytes,5,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	SessionId   string `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 发送端单调递增序号，用于排序和去重。
	Sequence uint64 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// UTC 时间仅用于跨系统审计；高频控制排序以单调时钟 + 序号为准。
	UtcTimeNs       int64  `protobuf:"varint,8,opt,name=utc_time_ns,json=utcTimeNs,proto3" json:"utc_time_ns,omitempty"`
	MonotonicTimeNs uint64 `protobuf:"varint,9,opt,name=monotonic_time_ns,json=monotonicTimeNs,proto3" json:"monotonic_time_ns,omitempty"`
	// 生存时间：到期后车端直接拒绝，不补发旧控制值。
	TtlMs uint32 `protobuf:"varint,10,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	// 贯穿 控制端→边缘→云服务→车端 的审计追踪 ID。
	TraceId string `protobuf:"bytes,11,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 具体消息的序列化字节（如 SignalUpdate / ControlCommand）。
	Payload []byte `protobuf:"bytes,12,opt,name=payload,proto3" json:"payload,omitempty"`
	// 完整性/认证标签（端到端）。
	AuthTag       []byte `protobuf:"bytes,13,opt,name=auth_tag,json=authTag,proto3" json:"auth_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_platform_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_platform_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSchemaMajor() uint32 {
	if x != nil {
		return x.SchemaMajor
	}
	return 0
}

func (x *Envelope) GetSchemaMinor() uint32 {
	if x != nil {
		return x.SchemaMinor
	}
	return 0
}

func (x *Envelope) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Envelope) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Envelope) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *Envelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetUtcTimeNs() int64 {
	if x != nil {
		return x.UtcTimeNs
	}
	return 0
}

func (x *Envelope) GetMonotonicTimeNs() uint64 {
	if x != nil {
		return x.MonotonicTimeNs
	}
	return 0
}

func (x *Envelope) GetTtlMs() uint32 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetAuthTag() []byte {
	if x != nil {
		return x.AuthTag
	}
	return nil
}

var File_platform_v1_envelope_proto protoreflect.FileDescriptor

const file_platform_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1aplatform/v1/envelope.proto\x12\vplatform.v1\"\x9f\x03\n" +
	"\bEnvelope\x12!\n" +
	"\fschema_major\x18\x01 \x01(\rR\vschemaMajor\x12!\n" +
	"\fschema_minor\x18\x02 \x01(\rR\vschemaMinor\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\tR\vmessageType\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x04 \x01(\tR\tvehicleId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x05 \x01(\tR\tgatewayId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x12\x1e\n" +
	"\vutc_time_ns\x18\b \x01(\x03R\tutcTimeNs\x12*\n" +
	"\x11monotonic_time_ns\x18\t \x01(\x04R\x0fmonotonicTimeNs\x12\x15\n" +
	"\x06ttl_ms\x18\n" +
	" \x01(\rR\x05ttlMs\x12\x19\n" +
	"\btrace_id\x18\v \x01(\tR\atraceId\x12\x18\n" +
	"\apayload\x18\f \x01(\fR\apayload\x12\x19\n" +
	"\bauth_tag\x18\r \x01(\fR\aauthTagB.Z,robot-agent/protocols/platform/v1;platformv1b\x06proto3"

var (
	file_platform_v1_envelope_proto_rawDescOnce sync.Once
	file_platform_v1_envelope_proto_rawDescData []byte
)

func file_platform_v1_envelope_proto_rawDescGZIP() []byte {
	file_platform_v1_envelope_proto_rawDescOnce.Do(func() {
		file_platform_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_envelope_proto_rawDesc), len(file_platform_v1_envelope_proto_rawDesc)))
	})
	return file_platform_v1_envelope_proto_rawDescData
}

var file_platform_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_platform_v1_envelope_proto_goTypes = []any{
	(*Envelope)(nil), // 0: platform.v1.Envelope
}
var file_platform_v1_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_platform_v1_envelope_proto_init() }
func file_platform_v1_envelope_proto_init() {
	if File_platform_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_envelope_proto_rawDesc), len(file_platform_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_envelope_proto_goTypes,
		DependencyIndexes: file_platform_v1_envelope_proto_depIdxs,
		MessageInfos:      file_platform_v1_envelope_proto_msgTypes,
	}.Build()
	File_platform_v1_envelope_proto = out.File
	file_platform_v1_envelope_proto_goTypes = nil
	file_platform_v1_envelope_proto_depIdxs = nil
}
