// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: platform/v1/local.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalFrame_Kind int32

const (
	LocalFrame_KIND_UNSPECIFIED      LocalFrame_Kind = 0
	LocalFrame_KIND_HELLO            LocalFrame_Kind = 1
	LocalFrame_KIND_ENVELOPE         LocalFrame_Kind = 2
	LocalFrame_KIND_ACTUATOR_REQUEST LocalFrame_Kind = 3
	LocalFrame_KIND_ACTUATOR_REPLY   LocalFrame_Kind = 4
)

// Enum value maps for LocalFrame_Kind.
var (
	LocalFrame_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_HELLO",
		2: "KIND_ENVELOPE",
		3: "KIND_ACTUATOR_REQUEST",
		4: "KIND_ACTUATOR_REPLY",
	}
	LocalFrame_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":      0,
		"KIND_HELLO":            1,
		"KIND_ENVELOPE":         2,
		"KIND_ACTUATOR_REQUEST": 3,
		"KIND_ACTUATOR_REPLY":   4,
	}
)

func (x LocalFrame_Kind) Enum() *LocalFrame_Kind {
	p := new(LocalFrame_Kind)
	*p = x
	return p
}

func (x LocalFrame_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocalFrame_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_local_proto_enumTypes[0].Descriptor()
}

func (LocalFrame_Kind) Type() protoreflect.EnumType {
	return &file_platform_v1_local_proto_enumTypes[0]
}

func (x LocalFrame_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocalFrame_Kind.Descriptor instead.
func (LocalFrame_Kind) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_local_proto_rawDescGZIP(), []int{0, 0}
}

// 车内 Unix Domain Socket 帧。长度前缀由传输层提供，消息本身必须是
// deterministic protobuf；禁止 JSON-line、换行分隔和未认证的角色声明。
type LocalFrame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Kind      LocalFrame_Kind        `protobuf:"varint,1,opt,name=kind,proto3,enum=platform.v1.LocalFrame_Kind" json:"kind,omitempty"`
	Component string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"` // adapter / arbiter / workspace
	Protocol  string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`   // platform.v1.local
	Envelope  *Envelope              `protobuf:"bytes,4,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*LocalFrame_ActuatorRequest
	//	*LocalFrame_ActuatorReply
	//	*LocalFrame_TerminalGrant
	//	*LocalFrame_WorkspaceData
	//	*LocalFrame_WorkspaceClose
	Body          isLocalFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalFrame) Reset() {
	*x = LocalFrame{}
	mi := &file_platform_v1_local_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalFrame) ProtoMessage() {}

func (x *LocalFrame) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_local_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalFrame.ProtoReflect.Descriptor instead.
func (*LocalFrame) Descriptor() ([]byte, []int) {
	return file_platform_v1_local_proto_rawDescGZIP(), []int{0}
}

func (x *LocalFrame) GetKind() LocalFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return LocalFrame_KIND_UNSPECIFIED
}

func (x *LocalFrame) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *LocalFrame) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *LocalFrame) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *LocalFrame) GetBody() isLocalFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *LocalFrame) GetActuatorRequest() *ActuatorRequest {
	if x != nil {
		if x, ok := x.Body.(*LocalFrame_ActuatorRequest); ok {
			return x.ActuatorRequest
		}
	}
	return nil
}

func (x *LocalFrame) GetActuatorReply() *ActuatorReply {
	if x != nil {
		if x, ok := x.Body.(*LocalFrame_ActuatorReply); ok {
			return x.ActuatorReply
		}
	}
	return nil
}

func (x *LocalFrame) GetTerminalGrant() *TerminalGrant {
	if x != nil {
		if x, ok := x.Body.(*LocalFrame_TerminalGrant); ok {
			return x.TerminalGrant
		}
	}
	return nil
}

func (x *LocalFrame) GetWorkspaceData() *WorkspaceData {
	if x != nil {
		if x, ok := x.Body.(*LocalFrame_WorkspaceData); ok {
			return x.WorkspaceData
		}
	}
	return nil
}

func (x *LocalFrame) GetWorkspaceClose() *WorkspaceClose {
	if x != nil {
		if x, ok := x.Body.(*LocalFrame_WorkspaceClose); ok {
			return x.WorkspaceClose
		}
	}
	return nil
}

type isLocalFrame_Body interface {
	isLocalFrame_Body()
}

type LocalFrame_ActuatorRequest struct {
	ActuatorRequest *ActuatorRequest `protobuf:"bytes,10,opt,name=actuator_request,json=actuatorRequest,proto3,oneof"`
}

type LocalFrame_ActuatorReply struct {
	ActuatorReply *ActuatorReply `protobuf:"bytes,11,opt,name=actuator_reply,json=actuatorReply,proto3,oneof"`
}

type LocalFrame_TerminalGrant struct {
	TerminalGrant *TerminalGrant `protobuf:"bytes,12,opt,name=terminal_grant,json=terminalGrant,proto3,oneof"`
}

type LocalFrame_WorkspaceData struct {
	WorkspaceData *WorkspaceData `protobuf:"bytes,13,opt,name=workspace_data,json=workspaceData,proto3,oneof"`
}

type LocalFrame_WorkspaceClose struct {
	WorkspaceClose *WorkspaceClose `protobuf:"bytes,14,opt,name=workspace_close,json=workspaceClose,proto3,oneof"`
}

func (*LocalFrame_ActuatorRequest) isLocalFrame_Body() {}

func (*LocalFrame_ActuatorReply) isLocalFrame_Body() {}

func (*LocalFrame_TerminalGrant) isLocalFrame_Body() {}

func (*LocalFrame_WorkspaceData) isLocalFrame_Body() {}

func (*LocalFrame_WorkspaceClose) isLocalFrame_Body() {}

type ActuatorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*ActuatorRequest_TargetMotion
	//	*ActuatorRequest_MinimalRiskReason
	Action        isActuatorRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActuatorRequest) Reset() {
	*x = ActuatorRequest{}
	mi := &file_platform_v1_local_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActuatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActuatorRequest) ProtoMessage() {}

func (x *ActuatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_local_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActuatorRequest.ProtoReflect.Descriptor instead.
func (*ActuatorRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_local_proto_rawDescGZIP(), []int{1}
}

func (x *ActuatorRequest) GetAction() isActuatorRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ActuatorRequest) GetTargetMotion() *TargetMotion {
	if x != nil {
		if x, ok := x.Action.(*ActuatorRequest_TargetMotion); ok {
			return x.TargetMotion
		}
	}
	return nil
}

func (x *ActuatorRequest) GetMinimalRiskReason() string {
	if x != nil {
		if x, ok := x.Action.(*ActuatorRequest_MinimalRiskReason); ok {
			return x.MinimalRiskReason
		}
	}
	return ""
}

type isActuatorRequest_Action interface {
	isActuatorRequest_Action()
}

type ActuatorRequest_TargetMotion struct {
	TargetMotion *TargetMotion `protobuf:"bytes,1,opt,name=target_motion,json=targetMotion,proto3,oneof"`
}

type ActuatorRequest_MinimalRiskReason struct {
	MinimalRiskReason string `protobuf:"bytes,2,opt,name=minimal_risk_reason,json=minimalRiskReason,proto3,oneof"`
}

func (*ActuatorRequest_TargetMotion) isActuatorRequest_Action() {}

func (*ActuatorRequest_MinimalRiskReason) isActuatorRequest_Action() {}

type ActuatorReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Ok                 bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error              string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	AppliedMonotonicNs uint64                 `protobuf:"varint,3,opt,name=applied_monotonic_ns,json=appliedMonotonicNs,proto3" json:"applied_monotonic_ns,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ActuatorReply) Reset() {
	*x = ActuatorReply{}
	mi := &file_platform_v1_local_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActuatorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActuatorReply) ProtoMessage() {}

func (x *ActuatorReply) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_local_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActuatorReply.ProtoReflect.Descriptor instead.
func (*ActuatorReply) Descriptor() ([]byte, []int) {
	return file_platform_v1_local_proto_rawDescGZIP(), []int{2}
}

func (x *ActuatorReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ActuatorReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ActuatorReply) GetAppliedMonotonicNs() uint64 {
	if x != nil {
		return x.AppliedMonotonicNs
	}
	return 0
}

var File_platform_v1_local_proto protoreflect.FileDescriptor

const file_platform_v1_local_proto_rawDesc = "" +
	"\n" +
	"\x17platform/v1/local.proto\x12\vplatform.v1\x1a\x19platform/v1/control.proto\x1a\x1aplatform/v1/envelope.proto\x1a\x1bplatform/v1/workspace.proto\"\x8a\x05\n" +
	"\n" +
	"LocalFrame\x120\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1c.platform.v1.LocalFrame.KindR\x04kind\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x121\n" +
	"\benvelope\x18\x04 \x01(\v2\x15.platform.v1.EnvelopeR\benvelope\x12I\n" +
	"\x10actuator_request\x18\n" +
	" \x01(\v2\x1c.platform.v1.ActuatorRequestH\x00R\x0factuatorRequest\x12C\n" +
	"\x0eactuator_reply\x18\v \x01(\v2\x1a.platform.v1.ActuatorReplyH\x00R\ractuatorReply\x12C\n" +
	"\x0eterminal_grant\x18\f \x01(\v2\x1a.platform.v1.TerminalGrantH\x00R\rterminalGrant\x12C\n" +
	"\x0eworkspace_data\x18\r \x01(\v2\x1a.platform.v1.WorkspaceDataH\x00R\rworkspaceData\x12F\n" +
	"\x0fworkspace_close\x18\x0e \x01(\v2\x1b.platform.v1.WorkspaceCloseH\x00R\x0eworkspaceClose\"s\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_HELLO\x10\x01\x12\x11\n" +
	"\rKIND_ENVELOPE\x10\x02\x12\x19\n" +
	"\x15KIND_ACTUATOR_REQUEST\x10\x03\x12\x17\n" +
	"\x13KIND_ACTUATOR_REPLY\x10\x04B\x06\n" +
	"\x04body\"\x8f\x01\n" +
	"\x0fActuatorRequest\x12@\n" +
	"\rtarget_motion\x18\x01 \x01(\v2\x19.platform.v1.TargetMotionH\x00R\ftargetMotion\x120\n" +
	"\x13minimal_risk_reason\x18\x02 \x01(\tH\x00R\x11minimalRiskReasonB\b\n" +
	"\x06action\"g\n" +
	"\rActuatorReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x120\n" +
	"\x14applied_monotonic_ns\x18\x03 \x01(\x04R\x12appliedMonotonicNsB.Z,robot-agent/protocols/platform/v1;platformv1b\x06proto3"

var (
	file_platform_v1_local_proto_rawDescOnce sync.Once
	file_platform_v1_local_proto_rawDescData []byte
)

func file_platform_v1_local_proto_rawDescGZIP() []byte {
	file_platform_v1_local_proto_rawDescOnce.Do(func() {
		file_platform_v1_local_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_local_proto_rawDesc), len(file_platform_v1_local_proto_rawDesc)))
	})
	return file_platform_v1_local_proto_rawDescData
}

var file_platform_v1_local_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platform_v1_local_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_platform_v1_local_proto_goTypes = []any{
	(LocalFrame_Kind)(0),    // 0: platform.v1.LocalFrame.Kind
	(*LocalFrame)(nil),      // 1: platform.v1.LocalFrame
	(*ActuatorRequest)(nil), // 2: platform.v1.ActuatorRequest
	(*ActuatorReply)(nil),   // 3: platform.v1.ActuatorReply
	(*Envelope)(nil),        // 4: platform.v1.Envelope
	(*TerminalGrant)(nil),   // 5: platform.v1.TerminalGrant
	(*WorkspaceData)(nil),   // 6: platform.v1.WorkspaceData
	(*WorkspaceClose)(nil),  // 7: platform.v1.WorkspaceClose
	(*TargetMotion)(nil),    // 8: platform.v1.TargetMotion
}
var file_platform_v1_local_proto_depIdxs = []int32{
	0, // 0: platform.v1.LocalFrame.kind:type_name -> platform.v1.LocalFrame.Kind
	4, // 1: platform.v1.LocalFrame.envelope:type_name -> platform.v1.Envelope
	2, // 2: platform.v1.LocalFrame.actuator_request:type_name -> platform.v1.ActuatorRequest
	3, // 3: platform.v1.LocalFrame.actuator_reply:type_name -> platform.v1.ActuatorReply
	5, // 4: platform.v1.LocalFrame.terminal_grant:type_name -> platform.v1.TerminalGrant
	6, // 5: platform.v1.LocalFrame.workspace_data:type_name -> platform.v1.WorkspaceData
	7, // 6: platform.v1.LocalFrame.workspace_close:type_name -> platform.v1.WorkspaceClose
	8, // 7: platform.v1.ActuatorRequest.target_motion:type_name -> platform.v1.TargetMotion
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_platform_v1_local_proto_init() }
func file_platform_v1_local_proto_init() {
	if File_platform_v1_local_proto != nil {
		return
	}
	file_platform_v1_control_proto_init()
	file_platform_v1_envelope_proto_init()
	file_platform_v1_workspace_proto_init()
	file_platform_v1_local_proto_msgTypes[0].OneofWrappers = []any{
		(*LocalFrame_ActuatorRequest)(nil),
		(*LocalFrame_ActuatorReply)(nil),
		(*LocalFrame_TerminalGrant)(nil),
		(*LocalFrame_WorkspaceData)(nil),
		(*LocalFrame_WorkspaceClose)(nil),
	}
	file_platform_v1_local_proto_msgTypes[1].OneofWrappers = []any{
		(*ActuatorRequest_TargetMotion)(nil),
		(*ActuatorRequest_MinimalRiskReason)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_local_proto_rawDesc), len(file_platform_v1_local_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_local_proto_goTypes,
		DependencyIndexes: file_platform_v1_local_proto_depIdxs,
		EnumInfos:         file_platform_v1_local_proto_enumTypes,
		MessageInfos:      file_platform_v1_local_proto_msgTypes,
	}.Build()
	File_platform_v1_local_proto = out.File
	file_platform_v1_local_proto_goTypes = nil
	file_platform_v1_local_proto_depIdxs = nil
}
