// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: platform/v1/map.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Map publication is a reliable vehicle command.  The command carries only
// immutable metadata; the vehicle obtains the content through its authenticated
// map channel and must return a signed acknowledgement before activation.
type MapPublicationAction int32

const (
	MapPublicationAction_MAP_PUBLICATION_ACTION_UNSPECIFIED MapPublicationAction = 0
	MapPublicationAction_MAP_PUBLICATION_ACTION_APPLY       MapPublicationAction = 1
	MapPublicationAction_MAP_PUBLICATION_ACTION_ROLLBACK    MapPublicationAction = 2
)

// Enum value maps for MapPublicationAction.
var (
	MapPublicationAction_name = map[int32]string{
		0: "MAP_PUBLICATION_ACTION_UNSPECIFIED",
		1: "MAP_PUBLICATION_ACTION_APPLY",
		2: "MAP_PUBLICATION_ACTION_ROLLBACK",
	}
	MapPublicationAction_value = map[string]int32{
		"MAP_PUBLICATION_ACTION_UNSPECIFIED": 0,
		"MAP_PUBLICATION_ACTION_APPLY":       1,
		"MAP_PUBLICATION_ACTION_ROLLBACK":    2,
	}
)

func (x MapPublicationAction) Enum() *MapPublicationAction {
	p := new(MapPublicationAction)
	*p = x
	return p
}

func (x MapPublicationAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MapPublicationAction) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_map_proto_enumTypes[0].Descriptor()
}

func (MapPublicationAction) Type() protoreflect.EnumType {
	return &file_platform_v1_map_proto_enumTypes[0]
}

func (x MapPublicationAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MapPublicationAction.Descriptor instead.
func (MapPublicationAction) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_map_proto_rawDescGZIP(), []int{0}
}

type MapPublicationResult int32

const (
	MapPublicationResult_MAP_PUBLICATION_RESULT_UNSPECIFIED MapPublicationResult = 0
	MapPublicationResult_MAP_PUBLICATION_RESULT_ACCEPTED    MapPublicationResult = 1
	MapPublicationResult_MAP_PUBLICATION_RESULT_REJECTED    MapPublicationResult = 2
	MapPublicationResult_MAP_PUBLICATION_RESULT_APPLIED     MapPublicationResult = 3
	MapPublicationResult_MAP_PUBLICATION_RESULT_FAILED      MapPublicationResult = 4
)

// Enum value maps for MapPublicationResult.
var (
	MapPublicationResult_name = map[int32]string{
		0: "MAP_PUBLICATION_RESULT_UNSPECIFIED",
		1: "MAP_PUBLICATION_RESULT_ACCEPTED",
		2: "MAP_PUBLICATION_RESULT_REJECTED",
		3: "MAP_PUBLICATION_RESULT_APPLIED",
		4: "MAP_PUBLICATION_RESULT_FAILED",
	}
	MapPublicationResult_value = map[string]int32{
		"MAP_PUBLICATION_RESULT_UNSPECIFIED": 0,
		"MAP_PUBLICATION_RESULT_ACCEPTED":    1,
		"MAP_PUBLICATION_RESULT_REJECTED":    2,
		"MAP_PUBLICATION_RESULT_APPLIED":     3,
		"MAP_PUBLICATION_RESULT_FAILED":      4,
	}
)

func (x MapPublicationResult) Enum() *MapPublicationResult {
	p := new(MapPublicationResult)
	*p = x
	return p
}

func (x MapPublicationResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MapPublicationResult) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_map_proto_enumTypes[1].Descriptor()
}

func (MapPublicationResult) Type() protoreflect.EnumType {
	return &file_platform_v1_map_proto_enumTypes[1]
}

func (x MapPublicationResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MapPublicationResult.Descriptor instead.
func (MapPublicationResult) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_map_proto_rawDescGZIP(), []int{1}
}

type MapPublicationCommand struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Version               uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Action                MapPublicationAction   `protobuf:"varint,2,opt,name=action,proto3,enum=platform.v1.MapPublicationAction" json:"action,omitempty"`
	PublicationId         string                 `protobuf:"bytes,3,opt,name=publication_id,json=publicationId,proto3" json:"publication_id,omitempty"`
	MapId                 string                 `protobuf:"bytes,4,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	VehicleId             string                 `protobuf:"bytes,5,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	MapVersion            uint32                 `protobuf:"varint,6,opt,name=map_version,json=mapVersion,proto3" json:"map_version,omitempty"`
	ContentSha256         string                 `protobuf:"bytes,7,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	CoordinateFrame       string                 `protobuf:"bytes,8,opt,name=coordinate_frame,json=coordinateFrame,proto3" json:"coordinate_frame,omitempty"`
	CompatibilityEntry    string                 `protobuf:"bytes,9,opt,name=compatibility_entry,json=compatibilityEntry,proto3" json:"compatibility_entry,omitempty"`
	RollbackPublicationId string                 `protobuf:"bytes,10,opt,name=rollback_publication_id,json=rollbackPublicationId,proto3" json:"rollback_publication_id,omitempty"`
	TraceId               string                 `protobuf:"bytes,11,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MapPublicationCommand) Reset() {
	*x = MapPublicationCommand{}
	mi := &file_platform_v1_map_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapPublicationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapPublicationCommand) ProtoMessage() {}

func (x *MapPublicationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_map_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapPublicationCommand.ProtoReflect.Descriptor instead.
func (*MapPublicationCommand) Descriptor() ([]byte, []int) {
	return file_platform_v1_map_proto_rawDescGZIP(), []int{0}
}

func (x *MapPublicationCommand) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MapPublicationCommand) GetAction() MapPublicationAction {
	if x != nil {
		return x.Action
	}
	return MapPublicationAction_MAP_PUBLICATION_ACTION_UNSPECIFIED
}

func (x *MapPublicationCommand) GetPublicationId() string {
	if x != nil {
		return x.PublicationId
	}
	return ""
}

func (x *MapPublicationCommand) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *MapPublicationCommand) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *MapPublicationCommand) GetMapVersion() uint32 {
	if x != nil {
		return x.MapVersion
	}
	return 0
}

func (x *MapPublicationCommand) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

func (x *MapPublicationCommand) GetCoordinateFrame() string {
	if x != nil {
		return x.CoordinateFrame
	}
	return ""
}

func (x *MapPublicationCommand) GetCompatibilityEntry() string {
	if x != nil {
		return x.CompatibilityEntry
	}
	return ""
}

func (x *MapPublicationCommand) GetRollbackPublicationId() string {
	if x != nil {
		return x.RollbackPublicationId
	}
	return ""
}

func (x *MapPublicationCommand) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type MapPublicationAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PublicationId   string                 `protobuf:"bytes,1,opt,name=publication_id,json=publicationId,proto3" json:"publication_id,omitempty"`
	MapId           string                 `protobuf:"bytes,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	VehicleId       string                 `protobuf:"bytes,3,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	MapVersion      uint32                 `protobuf:"varint,4,opt,name=map_version,json=mapVersion,proto3" json:"map_version,omitempty"`
	Result          MapPublicationResult   `protobuf:"varint,5,opt,name=result,proto3,enum=platform.v1.MapPublicationResult" json:"result,omitempty"`
	Detail          string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	AppliedAtUnixNs int64                  `protobuf:"varint,7,opt,name=applied_at_unix_ns,json=appliedAtUnixNs,proto3" json:"applied_at_unix_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MapPublicationAck) Reset() {
	*x = MapPublicationAck{}
	mi := &file_platform_v1_map_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapPublicationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapPublicationAck) ProtoMessage() {}

func (x *MapPublicationAck) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_map_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapPublicationAck.ProtoReflect.Descriptor instead.
func (*MapPublicationAck) Descriptor() ([]byte, []int) {
	return file_platform_v1_map_proto_rawDescGZIP(), []int{1}
}

func (x *MapPublicationAck) GetPublicationId() string {
	if x != nil {
		return x.PublicationId
	}
	return ""
}

func (x *MapPublicationAck) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *MapPublicationAck) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *MapPublicationAck) GetMapVersion() uint32 {
	if x != nil {
		return x.MapVersion
	}
	return 0
}

func (x *MapPublicationAck) GetResult() MapPublicationResult {
	if x != nil {
		return x.Result
	}
	return MapPublicationResult_MAP_PUBLICATION_RESULT_UNSPECIFIED
}

func (x *MapPublicationAck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *MapPublicationAck) GetAppliedAtUnixNs() int64 {
	if x != nil {
		return x.AppliedAtUnixNs
	}
	return 0
}

var File_platform_v1_map_proto protoreflect.FileDescriptor

const file_platform_v1_map_proto_rawDesc = "" +
	"\n" +
	"\x15platform/v1/map.proto\x12\vplatform.v1\"\xc0\x03\n" +
	"\x15MapPublicationCommand\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x129\n" +
	"\x06action\x18\x02 \x01(\x0e2!.platform.v1.MapPublicationActionR\x06action\x12%\n" +
	"\x0epublication_id\x18\x03 \x01(\tR\rpublicationId\x12\x15\n" +
	"\x06map_id\x18\x04 \x01(\tR\x05mapId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x05 \x01(\tR\tvehicleId\x12\x1f\n" +
	"\vmap_version\x18\x06 \x01(\rR\n" +
	"mapVersion\x12%\n" +
	"\x0econtent_sha256\x18\a \x01(\tR\rcontentSha256\x12)\n" +
	"\x10coordinate_frame\x18\b \x01(\tR\x0fcoordinateFrame\x12/\n" +
	"\x13compatibility_entry\x18\t \x01(\tR\x12compatibilityEntry\x126\n" +
	"\x17rollback_publication_id\x18\n" +
	" \x01(\tR\x15rollbackPublicationId\x12\x19\n" +
	"\btrace_id\x18\v \x01(\tR\atraceId\"\x91\x02\n" +
	"\x11MapPublicationAck\x12%\n" +
	"\x0epublication_id\x18\x01 \x01(\tR\rpublicationId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\tR\x05mapId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x03 \x01(\tR\tvehicleId\x12\x1f\n" +
	"\vmap_version\x18\x04 \x01(\rR\n" +
	"mapVersion\x129\n" +
	"\x06result\x18\x05 \x01(\x0e2!.platform.v1.MapPublicationResultR\x06result\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\x12+\n" +
	"\x12applied_at_unix_ns\x18\a \x01(\x03R\x0fappliedAtUnixNs*\x85\x01\n" +
	"\x14MapPublicationAction\x12&\n" +
	"\"MAP_PUBLICATION_ACTION_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cMAP_PUBLICATION_ACTION_APPLY\x10\x01\x12#\n" +
	"\x1fMAP_PUBLICATION_ACTION_ROLLBACK\x10\x02*\xcf\x01\n" +
	"\x14MapPublicationResult\x12&\n" +
	"\"MAP_PUBLICATION_RESULT_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fMAP_PUBLICATION_RESULT_ACCEPTED\x10\x01\x12#\n" +
	"\x1fMAP_PUBLICATION_RESULT_REJECTED\x10\x02\x12\"\n" +
	"\x1eMAP_PUBLICATION_RESULT_APPLIED\x10\x03\x12!\n" +
	"\x1dMAP_PUBLICATION_RESULT_FAILED\x10\x04B.Z,robot-agent/protocols/platform/v1;platformv1b\x06proto3"

var (
	file_platform_v1_map_proto_rawDescOnce sync.Once
	file_platform_v1_map_proto_rawDescData []byte
)

func file_platform_v1_map_proto_rawDescGZIP() []byte {
	file_platform_v1_map_proto_rawDescOnce.Do(func() {
		file_platform_v1_map_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_map_proto_rawDesc), len(file_platform_v1_map_proto_rawDesc)))
	})
	return file_platform_v1_map_proto_rawDescData
}

var file_platform_v1_map_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_platform_v1_map_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_platform_v1_map_proto_goTypes = []any{
	(MapPublicationAction)(0),     // 0: platform.v1.MapPublicationAction
	(MapPublicationResult)(0),     // 1: platform.v1.MapPublicationResult
	(*MapPublicationCommand)(nil), // 2: platform.v1.MapPublicationCommand
	(*MapPublicationAck)(nil),     // 3: platform.v1.MapPublicationAck
}
var file_platform_v1_map_proto_depIdxs = []int32{
	0, // 0: platform.v1.MapPublicationCommand.action:type_name -> platform.v1.MapPublicationAction
	1, // 1: platform.v1.MapPublicationAck.result:type_name -> platform.v1.MapPublicationResult
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_platform_v1_map_proto_init() }
func file_platform_v1_map_proto_init() {
	if File_platform_v1_map_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_map_proto_rawDesc), len(file_platform_v1_map_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_map_proto_goTypes,
		DependencyIndexes: file_platform_v1_map_proto_depIdxs,
		EnumInfos:         file_platform_v1_map_proto_enumTypes,
		MessageInfos:      file_platform_v1_map_proto_msgTypes,
	}.Build()
	File_platform_v1_map_proto = out.File
	file_platform_v1_map_proto_goTypes = nil
	file_platform_v1_map_proto_depIdxs = nil
}
