// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: platform/v1/navigation.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NavigationAction int32

const (
	NavigationAction_NAVIGATION_ACTION_UNSPECIFIED NavigationAction = 0
	NavigationAction_NAVIGATION_ACTION_DISPATCH    NavigationAction = 1
	NavigationAction_NAVIGATION_ACTION_CANCEL      NavigationAction = 2
)

// Enum value maps for NavigationAction.
var (
	NavigationAction_name = map[int32]string{
		0: "NAVIGATION_ACTION_UNSPECIFIED",
		1: "NAVIGATION_ACTION_DISPATCH",
		2: "NAVIGATION_ACTION_CANCEL",
	}
	NavigationAction_value = map[string]int32{
		"NAVIGATION_ACTION_UNSPECIFIED": 0,
		"NAVIGATION_ACTION_DISPATCH":    1,
		"NAVIGATION_ACTION_CANCEL":      2,
	}
)

func (x NavigationAction) Enum() *NavigationAction {
	p := new(NavigationAction)
	*p = x
	return p
}

func (x NavigationAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NavigationAction) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_navigation_proto_enumTypes[0].Descriptor()
}

func (NavigationAction) Type() protoreflect.EnumType {
	return &file_platform_v1_navigation_proto_enumTypes[0]
}

func (x NavigationAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NavigationAction.Descriptor instead.
func (NavigationAction) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_navigation_proto_rawDescGZIP(), []int{0}
}

// Vehicle-side acknowledgement for a navigation command.  Broker delivery is
// not execution: the platform only changes the route state after this signed
// vehicle-originated acknowledgement is accepted.
type NavigationResult int32

const (
	NavigationResult_NAVIGATION_RESULT_UNSPECIFIED NavigationResult = 0
	NavigationResult_NAVIGATION_RESULT_ACCEPTED    NavigationResult = 1
	NavigationResult_NAVIGATION_RESULT_STARTED     NavigationResult = 2
	NavigationResult_NAVIGATION_RESULT_COMPLETED   NavigationResult = 3
	NavigationResult_NAVIGATION_RESULT_REJECTED    NavigationResult = 4
	NavigationResult_NAVIGATION_RESULT_CANCELLED   NavigationResult = 5
	NavigationResult_NAVIGATION_RESULT_FAILED      NavigationResult = 6
)

// Enum value maps for NavigationResult.
var (
	NavigationResult_name = map[int32]string{
		0: "NAVIGATION_RESULT_UNSPECIFIED",
		1: "NAVIGATION_RESULT_ACCEPTED",
		2: "NAVIGATION_RESULT_STARTED",
		3: "NAVIGATION_RESULT_COMPLETED",
		4: "NAVIGATION_RESULT_REJECTED",
		5: "NAVIGATION_RESULT_CANCELLED",
		6: "NAVIGATION_RESULT_FAILED",
	}
	NavigationResult_value = map[string]int32{
		"NAVIGATION_RESULT_UNSPECIFIED": 0,
		"NAVIGATION_RESULT_ACCEPTED":    1,
		"NAVIGATION_RESULT_STARTED":     2,
		"NAVIGATION_RESULT_COMPLETED":   3,
		"NAVIGATION_RESULT_REJECTED":    4,
		"NAVIGATION_RESULT_CANCELLED":   5,
		"NAVIGATION_RESULT_FAILED":      6,
	}
)

func (x NavigationResult) Enum() *NavigationResult {
	p := new(NavigationResult)
	*p = x
	return p
}

func (x NavigationResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NavigationResult) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_navigation_proto_enumTypes[1].Descriptor()
}

func (NavigationResult) Type() protoreflect.EnumType {
	return &file_platform_v1_navigation_proto_enumTypes[1]
}

func (x NavigationResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NavigationResult.Descriptor instead.
func (NavigationResult) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_navigation_proto_rawDescGZIP(), []int{1}
}

type NavigationPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XM            float64                `protobuf:"fixed64,2,opt,name=x_m,json=xM,proto3" json:"x_m,omitempty"`
	YM            float64                `protobuf:"fixed64,3,opt,name=y_m,json=yM,proto3" json:"y_m,omitempty"`
	AtUnixNs      int64                  `protobuf:"varint,4,opt,name=at_unix_ns,json=atUnixNs,proto3" json:"at_unix_ns,omitempty"`
	DwellS        float64                `protobuf:"fixed64,5,opt,name=dwell_s,json=dwellS,proto3" json:"dwell_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigationPoint) Reset() {
	*x = NavigationPoint{}
	mi := &file_platform_v1_navigation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigationPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationPoint) ProtoMessage() {}

func (x *NavigationPoint) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_navigation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationPoint.ProtoReflect.Descriptor instead.
func (*NavigationPoint) Descriptor() ([]byte, []int) {
	return file_platform_v1_navigation_proto_rawDescGZIP(), []int{0}
}

func (x *NavigationPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NavigationPoint) GetXM() float64 {
	if x != nil {
		return x.XM
	}
	return 0
}

func (x *NavigationPoint) GetYM() float64 {
	if x != nil {
		return x.YM
	}
	return 0
}

func (x *NavigationPoint) GetAtUnixNs() int64 {
	if x != nil {
		return x.AtUnixNs
	}
	return 0
}

func (x *NavigationPoint) GetDwellS() float64 {
	if x != nil {
		return x.DwellS
	}
	return 0
}

type NavigationCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Action        NavigationAction       `protobuf:"varint,2,opt,name=action,proto3,enum=platform.v1.NavigationAction" json:"action,omitempty"`
	RouteId       string                 `protobuf:"bytes,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	VehicleId     string                 `protobuf:"bytes,4,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Points        []*NavigationPoint     `protobuf:"bytes,7,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigationCommand) Reset() {
	*x = NavigationCommand{}
	mi := &file_platform_v1_navigation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationCommand) ProtoMessage() {}

func (x *NavigationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_navigation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationCommand.ProtoReflect.Descriptor instead.
func (*NavigationCommand) Descriptor() ([]byte, []int) {
	return file_platform_v1_navigation_proto_rawDescGZIP(), []int{1}
}

func (x *NavigationCommand) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NavigationCommand) GetAction() NavigationAction {
	if x != nil {
		return x.Action
	}
	return NavigationAction_NAVIGATION_ACTION_UNSPECIFIED
}

func (x *NavigationCommand) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *NavigationCommand) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *NavigationCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NavigationCommand) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *NavigationCommand) GetPoints() []*NavigationPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type NavigationAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Action          NavigationAction       `protobuf:"varint,2,opt,name=action,proto3,enum=platform.v1.NavigationAction" json:"action,omitempty"`
	RouteId         string                 `protobuf:"bytes,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	VehicleId       string                 `protobuf:"bytes,4,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Result          NavigationResult       `protobuf:"varint,5,opt,name=result,proto3,enum=platform.v1.NavigationResult" json:"result,omitempty"`
	Detail          string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	CurrentPoint    uint32                 `protobuf:"varint,7,opt,name=current_point,json=currentPoint,proto3" json:"current_point,omitempty"`
	AppliedAtUnixNs int64                  `protobuf:"varint,8,opt,name=applied_at_unix_ns,json=appliedAtUnixNs,proto3" json:"applied_at_unix_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NavigationAck) Reset() {
	*x = NavigationAck{}
	mi := &file_platform_v1_navigation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationAck) ProtoMessage() {}

func (x *NavigationAck) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_navigation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationAck.ProtoReflect.Descriptor instead.
func (*NavigationAck) Descriptor() ([]byte, []int) {
	return file_platform_v1_navigation_proto_rawDescGZIP(), []int{2}
}

func (x *NavigationAck) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NavigationAck) GetAction() NavigationAction {
	if x != nil {
		return x.Action
	}
	return NavigationAction_NAVIGATION_ACTION_UNSPECIFIED
}

func (x *NavigationAck) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *NavigationAck) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *NavigationAck) GetResult() NavigationResult {
	if x != nil {
		return x.Result
	}
	return NavigationResult_NAVIGATION_RESULT_UNSPECIFIED
}

func (x *NavigationAck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *NavigationAck) GetCurrentPoint() uint32 {
	if x != nil {
		return x.CurrentPoint
	}
	return 0
}

func (x *NavigationAck) GetAppliedAtUnixNs() int64 {
	if x != nil {
		return x.AppliedAtUnixNs
	}
	return 0
}

var File_platform_v1_navigation_proto protoreflect.FileDescriptor

const file_platform_v1_navigation_proto_rawDesc = "" +
	"\n" +
	"\x1cplatform/v1/navigation.proto\x12\vplatform.v1\"~\n" +
	"\x0fNavigationPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0f\n" +
	"\x03x_m\x18\x02 \x01(\x01R\x02xM\x12\x0f\n" +
	"\x03y_m\x18\x03 \x01(\x01R\x02yM\x12\x1c\n" +
	"\n" +
	"at_unix_ns\x18\x04 \x01(\x03R\batUnixNs\x12\x17\n" +
	"\adwell_s\x18\x05 \x01(\x01R\x06dwellS\"\x83\x02\n" +
	"\x11NavigationCommand\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x125\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1d.platform.v1.NavigationActionR\x06action\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\tR\arouteId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x04 \x01(\tR\tvehicleId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x124\n" +
	"\x06points\x18\a \x03(\v2\x1c.platform.v1.NavigationPointR\x06points\"\xbb\x02\n" +
	"\rNavigationAck\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x125\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1d.platform.v1.NavigationActionR\x06action\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\tR\arouteId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x04 \x01(\tR\tvehicleId\x125\n" +
	"\x06result\x18\x05 \x01(\x0e2\x1d.platform.v1.NavigationResultR\x06result\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\x12#\n" +
	"\rcurrent_point\x18\a \x01(\rR\fcurrentPoint\x12+\n" +
	"\x12applied_at_unix_ns\x18\b \x01(\x03R\x0fappliedAtUnixNs*s\n" +
	"\x10NavigationAction\x12!\n" +
	"\x1dNAVIGATION_ACTION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNAVIGATION_ACTION_DISPATCH\x10\x01\x12\x1c\n" +
	"\x18NAVIGATION_ACTION_CANCEL\x10\x02*\xf4\x01\n" +
	"\x10NavigationResult\x12!\n" +
	"\x1dNAVIGATION_RESULT_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNAVIGATION_RESULT_ACCEPTED\x10\x01\x12\x1d\n" +
	"\x19NAVIGATION_RESULT_STARTED\x10\x02\x12\x1f\n" +
	"\x1bNAVIGATION_RESULT_COMPLETED\x10\x03\x12\x1e\n" +
	"\x1aNAVIGATION_RESULT_REJECTED\x10\x04\x12\x1f\n" +
	"\x1bNAVIGATION_RESULT_CANCELLED\x10\x05\x12\x1c\n" +
	"\x18NAVIGATION_RESULT_FAILED\x10\x06B.Z,robot-agent/protocols/platform/v1;platformv1b\x06proto3"

var (
	file_platform_v1_navigation_proto_rawDescOnce sync.Once
	file_platform_v1_navigation_proto_rawDescData []byte
)

func file_platform_v1_navigation_proto_rawDescGZIP() []byte {
	file_platform_v1_navigation_proto_rawDescOnce.Do(func() {
		file_platform_v1_navigation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_navigation_proto_rawDesc), len(file_platform_v1_navigation_proto_rawDesc)))
	})
	return file_platform_v1_navigation_proto_rawDescData
}

var file_platform_v1_navigation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_platform_v1_navigation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_platform_v1_navigation_proto_goTypes = []any{
	(NavigationAction)(0),     // 0: platform.v1.NavigationAction
	(NavigationResult)(0),     // 1: platform.v1.NavigationResult
	(*NavigationPoint)(nil),   // 2: platform.v1.NavigationPoint
	(*NavigationCommand)(nil), // 3: platform.v1.NavigationCommand
	(*NavigationAck)(nil),     // 4: platform.v1.NavigationAck
}
var file_platform_v1_navigation_proto_depIdxs = []int32{
	0, // 0: platform.v1.NavigationCommand.action:type_name -> platform.v1.NavigationAction
	2, // 1: platform.v1.NavigationCommand.points:type_name -> platform.v1.NavigationPoint
	0, // 2: platform.v1.NavigationAck.action:type_name -> platform.v1.NavigationAction
	1, // 3: platform.v1.NavigationAck.result:type_name -> platform.v1.NavigationResult
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_platform_v1_navigation_proto_init() }
func file_platform_v1_navigation_proto_init() {
	if File_platform_v1_navigation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_navigation_proto_rawDesc), len(file_platform_v1_navigation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_navigation_proto_goTypes,
		DependencyIndexes: file_platform_v1_navigation_proto_depIdxs,
		EnumInfos:         file_platform_v1_navigation_proto_enumTypes,
		MessageInfos:      file_platform_v1_navigation_proto_msgTypes,
	}.Build()
	File_platform_v1_navigation_proto = out.File
	file_platform_v1_navigation_proto_goTypes = nil
	file_platform_v1_navigation_proto_depIdxs = nil
}
