// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: platform/v1/telemetry.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 信号质量。
type SignalQuality int32

const (
	SignalQuality_SIGNAL_QUALITY_UNSPECIFIED SignalQuality = 0
	SignalQuality_SIGNAL_QUALITY_GOOD        SignalQuality = 1
	SignalQuality_SIGNAL_QUALITY_STALE       SignalQuality = 2 // 数据过期但仍可用
	SignalQuality_SIGNAL_QUALITY_MISSING     SignalQuality = 3 // 源缺失
	SignalQuality_SIGNAL_QUALITY_INVALID     SignalQuality = 4 // 校验失败
)

// Enum value maps for SignalQuality.
var (
	SignalQuality_name = map[int32]string{
		0: "SIGNAL_QUALITY_UNSPECIFIED",
		1: "SIGNAL_QUALITY_GOOD",
		2: "SIGNAL_QUALITY_STALE",
		3: "SIGNAL_QUALITY_MISSING",
		4: "SIGNAL_QUALITY_INVALID",
	}
	SignalQuality_value = map[string]int32{
		"SIGNAL_QUALITY_UNSPECIFIED": 0,
		"SIGNAL_QUALITY_GOOD":        1,
		"SIGNAL_QUALITY_STALE":       2,
		"SIGNAL_QUALITY_MISSING":     3,
		"SIGNAL_QUALITY_INVALID":     4,
	}
)

func (x SignalQuality) Enum() *SignalQuality {
	p := new(SignalQuality)
	*p = x
	return p
}

func (x SignalQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_telemetry_proto_enumTypes[0].Descriptor()
}

func (SignalQuality) Type() protoreflect.EnumType {
	return &file_platform_v1_telemetry_proto_enumTypes[0]
}

func (x SignalQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalQuality.Descriptor instead.
func (SignalQuality) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

type DoubleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleList) Reset() {
	*x = DoubleList{}
	mi := &file_platform_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleList) ProtoMessage() {}

func (x *DoubleList) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleList.ProtoReflect.Descriptor instead.
func (*DoubleList) Descriptor() ([]byte, []int) {
	return file_platform_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *DoubleList) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

// 信号值：VSS 风格的通用取值。
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_Number
	//	*Value_Boolean
	//	*Value_Text
	//	*Value_Raw
	//	*Value_NumberList
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_platform_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_platform_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetNumber() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Number); ok {
			return x.Number
		}
	}
	return 0
}

func (x *Value) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

func (x *Value) GetText() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Value) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *Value) GetNumberList() *DoubleList {
	if x != nil {
		if x, ok := x.Kind.(*Value_NumberList); ok {
			return x.NumberList
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_Number struct {
	Number float64 `protobuf:"fixed64,1,opt,name=number,proto3,oneof"`
}

type Value_Boolean struct {
	Boolean bool `protobuf:"varint,2,opt,name=boolean,proto3,oneof"`
}

type Value_Text struct {
	Text string `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type Value_Raw struct {
	Raw []byte `protobuf:"bytes,4,opt,name=raw,proto3,oneof"`
}

type Value_NumberList struct {
	NumberList *DoubleList `protobuf:"bytes,5,opt,name=number_list,json=numberList,proto3,oneof"`
}

func (*Value_Number) isValue_Kind() {}

func (*Value_Boolean) isValue_Kind() {}

func (*Value_Text) isValue_Kind() {}

func (*Value_Raw) isValue_Kind() {}

func (*Value_NumberList) isValue_Kind() {}

// 单条信号：path 使用 VSS 路径（Vehicle.Speed / Platform.Autonomy.* 等）。
type Signal struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Path              string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value             *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	SampleMonotonicNs uint64                 `protobuf:"varint,3,opt,name=sample_monotonic_ns,json=sampleMonotonicNs,proto3" json:"sample_monotonic_ns,omitempty"`
	SampleUtcNs       int64                  `protobuf:"varint,4,opt,name=sample_utc_ns,json=sampleUtcNs,proto3" json:"sample_utc_ns,omitempty"`
	Quality           SignalQuality          `protobuf:"varint,5,opt,name=quality,proto3,enum=platform.v1.SignalQuality" json:"quality,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_platform_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_platform_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *Signal) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Signal) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Signal) GetSampleMonotonicNs() uint64 {
	if x != nil {
		return x.SampleMonotonicNs
	}
	return 0
}

func (x *Signal) GetSampleUtcNs() int64 {
	if x != nil {
		return x.SampleUtcNs
	}
	return 0
}

func (x *Signal) GetQuality() SignalQuality {
	if x != nil {
		return x.Quality
	}
	return SignalQuality_SIGNAL_QUALITY_UNSPECIFIED
}

// 一批信号更新（遥测主消息）。
type SignalUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*Signal              `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalUpdate) Reset() {
	*x = SignalUpdate{}
	mi := &file_platform_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalUpdate) ProtoMessage() {}

func (x *SignalUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalUpdate.ProtoReflect.Descriptor instead.
func (*SignalUpdate) Descriptor() ([]byte, []int) {
	return file_platform_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *SignalUpdate) GetSignals() []*Signal {
	if x != nil {
		return x.Signals
	}
	return nil
}

// 单条链路状态（双链路各报一条）。
type LinkStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Up                 bool                   `protobuf:"varint,1,opt,name=up,proto3" json:"up,omitempty"`
	Carrier            string                 `protobuf:"bytes,2,opt,name=carrier,proto3" json:"carrier,omitempty"` // 运营商
	RttMs              uint32                 `protobuf:"varint,3,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	PacketLossFraction float64                `protobuf:"fixed64,4,opt,name=packet_loss_fraction,json=packetLossFraction,proto3" json:"packet_loss_fraction,omitempty"` // 0..1
	TxBytesPerS        uint64                 `protobuf:"varint,5,opt,name=tx_bytes_per_s,json=txBytesPerS,proto3" json:"tx_bytes_per_s,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LinkStatus) Reset() {
	*x = LinkStatus{}
	mi := &file_platform_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStatus) ProtoMessage() {}

func (x *LinkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStatus.ProtoReflect.Descriptor instead.
func (*LinkStatus) Descriptor() ([]byte, []int) {
	return file_platform_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *LinkStatus) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *LinkStatus) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *LinkStatus) GetRttMs() uint32 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *LinkStatus) GetPacketLossFraction() float64 {
	if x != nil {
		return x.PacketLossFraction
	}
	return 0
}

func (x *LinkStatus) GetTxBytesPerS() uint64 {
	if x != nil {
		return x.TxBytesPerS
	}
	return 0
}

// Gateway 自身状态（低频上报）。
type GatewayStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UptimeS              uint64                 `protobuf:"varint,1,opt,name=uptime_s,json=uptimeS,proto3" json:"uptime_s,omitempty"`
	LinkA                *LinkStatus            `protobuf:"bytes,2,opt,name=link_a,json=linkA,proto3" json:"link_a,omitempty"`
	LinkB                *LinkStatus            `protobuf:"bytes,3,opt,name=link_b,json=linkB,proto3" json:"link_b,omitempty"`
	AdapterVersion       string                 `protobuf:"bytes,4,opt,name=adapter_version,json=adapterVersion,proto3" json:"adapter_version,omitempty"`
	SafetyArbiterVersion string                 `protobuf:"bytes,5,opt,name=safety_arbiter_version,json=safetyArbiterVersion,proto3" json:"safety_arbiter_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GatewayStatus) Reset() {
	*x = GatewayStatus{}
	mi := &file_platform_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayStatus) ProtoMessage() {}

func (x *GatewayStatus) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayStatus.ProtoReflect.Descriptor instead.
func (*GatewayStatus) Descriptor() ([]byte, []int) {
	return file_platform_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *GatewayStatus) GetUptimeS() uint64 {
	if x != nil {
		return x.UptimeS
	}
	return 0
}

func (x *GatewayStatus) GetLinkA() *LinkStatus {
	if x != nil {
		return x.LinkA
	}
	return nil
}

func (x *GatewayStatus) GetLinkB() *LinkStatus {
	if x != nil {
		return x.LinkB
	}
	return nil
}

func (x *GatewayStatus) GetAdapterVersion() string {
	if x != nil {
		return x.AdapterVersion
	}
	return ""
}

func (x *GatewayStatus) GetSafetyArbiterVersion() string {
	if x != nil {
		return x.SafetyArbiterVersion
	}
	return ""
}

// 心跳（保活用，无内容）。
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_platform_v1_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_platform_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

var File_platform_v1_telemetry_proto protoreflect.FileDescriptor

const file_platform_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1bplatform/v1/telemetry.proto\x12\vplatform.v1\"$\n" +
	"\n" +
	"DoubleList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\"\xab\x01\n" +
	"\x05Value\x12\x18\n" +
	"\x06number\x18\x01 \x01(\x01H\x00R\x06number\x12\x1a\n" +
	"\aboolean\x18\x02 \x01(\bH\x00R\aboolean\x12\x14\n" +
	"\x04text\x18\x03 \x01(\tH\x00R\x04text\x12\x12\n" +
	"\x03raw\x18\x04 \x01(\fH\x00R\x03raw\x12:\n" +
	"\vnumber_list\x18\x05 \x01(\v2\x17.platform.v1.DoubleListH\x00R\n" +
	"numberListB\x06\n" +
	"\x04kind\"\xd0\x01\n" +
	"\x06Signal\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.platform.v1.ValueR\x05value\x12.\n" +
	"\x13sample_monotonic_ns\x18\x03 \x01(\x04R\x11sampleMonotonicNs\x12\"\n" +
	"\rsample_utc_ns\x18\x04 \x01(\x03R\vsampleUtcNs\x124\n" +
	"\aquality\x18\x05 \x01(\x0e2\x1a.platform.v1.SignalQualityR\aquality\"=\n" +
	"\fSignalUpdate\x12-\n" +
	"\asignals\x18\x01 \x03(\v2\x13.platform.v1.SignalR\asignals\"\xa4\x01\n" +
	"\n" +
	"LinkStatus\x12\x0e\n" +
	"\x02up\x18\x01 \x01(\bR\x02up\x12\x18\n" +
	"\acarrier\x18\x02 \x01(\tR\acarrier\x12\x15\n" +
	"\x06rtt_ms\x18\x03 \x01(\rR\x05rttMs\x120\n" +
	"\x14packet_loss_fraction\x18\x04 \x01(\x01R\x12packetLossFraction\x12#\n" +
	"\x0etx_bytes_per_s\x18\x05 \x01(\x04R\vtxBytesPerS\"\xe9\x01\n" +
	"\rGatewayStatus\x12\x19\n" +
	"\buptime_s\x18\x01 \x01(\x04R\auptimeS\x12.\n" +
	"\x06link_a\x18\x02 \x01(\v2\x17.platform.v1.LinkStatusR\x05linkA\x12.\n" +
	"\x06link_b\x18\x03 \x01(\v2\x17.platform.v1.LinkStatusR\x05linkB\x12'\n" +
	"\x0fadapter_version\x18\x04 \x01(\tR\x0eadapterVersion\x124\n" +
	"\x16safety_arbiter_version\x18\x05 \x01(\tR\x14safetyArbiterVersion\"\v\n" +
	"\tHeartbeat*\x9a\x01\n" +
	"\rSignalQuality\x12\x1e\n" +
	"\x1aSIGNAL_QUALITY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SIGNAL_QUALITY_GOOD\x10\x01\x12\x18\n" +
	"\x14SIGNAL_QUALITY_STALE\x10\x02\x12\x1a\n" +
	"\x16SIGNAL_QUALITY_MISSING\x10\x03\x12\x1a\n" +
	"\x16SIGNAL_QUALITY_INVALID\x10\x04B.Z,robot-agent/protocols/platform/v1;platformv1b\x06proto3"

var (
	file_platform_v1_telemetry_proto_rawDescOnce sync.Once
	file_platform_v1_telemetry_proto_rawDescData []byte
)

func file_platform_v1_telemetry_proto_rawDescGZIP() []byte {
	file_platform_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_platform_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_telemetry_proto_rawDesc), len(file_platform_v1_telemetry_proto_rawDesc)))
	})
	return file_platform_v1_telemetry_proto_rawDescData
}

var file_platform_v1_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platform_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_platform_v1_telemetry_proto_goTypes = []any{
	(SignalQuality)(0),    // 0: platform.v1.SignalQuality
	(*DoubleList)(nil),    // 1: platform.v1.DoubleList
	(*Value)(nil),         // 2: platform.v1.Value
	(*Signal)(nil),        // 3: platform.v1.Signal
	(*SignalUpdate)(nil),  // 4: platform.v1.SignalUpdate
	(*LinkStatus)(nil),    // 5: platform.v1.LinkStatus
	(*GatewayStatus)(nil), // 6: platform.v1.GatewayStatus
	(*Heartbeat)(nil),     // 7: platform.v1.Heartbeat
}
var file_platform_v1_telemetry_proto_depIdxs = []int32{
	1, // 0: platform.v1.Value.number_list:type_name -> platform.v1.DoubleList
	2, // 1: platform.v1.Signal.value:type_name -> platform.v1.Value
	0, // 2: platform.v1.Signal.quality:type_name -> platform.v1.SignalQuality
	3, // 3: platform.v1.SignalUpdate.signals:type_name -> platform.v1.Signal
	5, // 4: platform.v1.GatewayStatus.link_a:type_name -> platform.v1.LinkStatus
	5, // 5: platform.v1.GatewayStatus.link_b:type_name -> platform.v1.LinkStatus
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_platform_v1_telemetry_proto_init() }
func file_platform_v1_telemetry_proto_init() {
	if File_platform_v1_telemetry_proto != nil {
		return
	}
	file_platform_v1_telemetry_proto_msgTypes[1].OneofWrappers = []any{
		(*Value_Number)(nil),
		(*Value_Boolean)(nil),
		(*Value_Text)(nil),
		(*Value_Raw)(nil),
		(*Value_NumberList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_telemetry_proto_rawDesc), len(file_platform_v1_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_platform_v1_telemetry_proto_depIdxs,
		EnumInfos:         file_platform_v1_telemetry_proto_enumTypes,
		MessageInfos:      file_platform_v1_telemetry_proto_msgTypes,
	}.Build()
	File_platform_v1_telemetry_proto = out.File
	file_platform_v1_telemetry_proto_goTypes = nil
	file_platform_v1_telemetry_proto_depIdxs = nil
}
