// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: platform/v1/workspace.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 远程维护/工作空间安全消息。终端令牌只能由受信 Authority 签发，
// 车端 Agent 还必须验证外层 Envelope HMAC；令牌本身不作为控制租约使用。
type TerminalGrant struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	VehicleId          string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	GatewayId          string                 `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	SessionId          string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TerminalToken      []byte                 `protobuf:"bytes,5,opt,name=terminal_token,json=terminalToken,proto3" json:"terminal_token,omitempty"`
	DriverId           string                 `protobuf:"bytes,6,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DeviceId           string                 `protobuf:"bytes,7,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ValidUntilUnixNs   int64                  `protobuf:"varint,8,opt,name=valid_until_unix_ns,json=validUntilUnixNs,proto3" json:"valid_until_unix_ns,omitempty"`
	IssuedAtUnixNs     int64                  `protobuf:"varint,9,opt,name=issued_at_unix_ns,json=issuedAtUnixNs,proto3" json:"issued_at_unix_ns,omitempty"`
	AuthorityKeyId     string                 `protobuf:"bytes,10,opt,name=authority_key_id,json=authorityKeyId,proto3" json:"authority_key_id,omitempty"`
	AuthoritySignature []byte                 `protobuf:"bytes,11,opt,name=authority_signature,json=authoritySignature,proto3" json:"authority_signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TerminalGrant) Reset() {
	*x = TerminalGrant{}
	mi := &file_platform_v1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalGrant) ProtoMessage() {}

func (x *TerminalGrant) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalGrant.ProtoReflect.Descriptor instead.
func (*TerminalGrant) Descriptor() ([]byte, []int) {
	return file_platform_v1_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *TerminalGrant) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TerminalGrant) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *TerminalGrant) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *TerminalGrant) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalGrant) GetTerminalToken() []byte {
	if x != nil {
		return x.TerminalToken
	}
	return nil
}

func (x *TerminalGrant) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *TerminalGrant) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TerminalGrant) GetValidUntilUnixNs() int64 {
	if x != nil {
		return x.ValidUntilUnixNs
	}
	return 0
}

func (x *TerminalGrant) GetIssuedAtUnixNs() int64 {
	if x != nil {
		return x.IssuedAtUnixNs
	}
	return 0
}

func (x *TerminalGrant) GetAuthorityKeyId() string {
	if x != nil {
		return x.AuthorityKeyId
	}
	return ""
}

func (x *TerminalGrant) GetAuthoritySignature() []byte {
	if x != nil {
		return x.AuthoritySignature
	}
	return nil
}

type WorkspaceData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceData) Reset() {
	*x = WorkspaceData{}
	mi := &file_platform_v1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceData) ProtoMessage() {}

func (x *WorkspaceData) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceData.ProtoReflect.Descriptor instead.
func (*WorkspaceData) Descriptor() ([]byte, []int) {
	return file_platform_v1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *WorkspaceData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkspaceData) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *WorkspaceData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WorkspaceClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceClose) Reset() {
	*x = WorkspaceClose{}
	mi := &file_platform_v1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceClose) ProtoMessage() {}

func (x *WorkspaceClose) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceClose.ProtoReflect.Descriptor instead.
func (*WorkspaceClose) Descriptor() ([]byte, []int) {
	return file_platform_v1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *WorkspaceClose) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkspaceClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_platform_v1_workspace_proto protoreflect.FileDescriptor

const file_platform_v1_workspace_proto_rawDesc = "" +
	"\n" +
	"\x1bplatform/v1/workspace.proto\x12\vplatform.v1\"\x9c\x03\n" +
	"\rTerminalGrant\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x03 \x01(\tR\tgatewayId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12%\n" +
	"\x0eterminal_token\x18\x05 \x01(\fR\rterminalToken\x12\x1b\n" +
	"\tdriver_id\x18\x06 \x01(\tR\bdriverId\x12\x1b\n" +
	"\tdevice_id\x18\a \x01(\tR\bdeviceId\x12-\n" +
	"\x13valid_until_unix_ns\x18\b \x01(\x03R\x10validUntilUnixNs\x12)\n" +
	"\x11issued_at_unix_ns\x18\t \x01(\x03R\x0eissuedAtUnixNs\x12(\n" +
	"\x10authority_key_id\x18\n" +
	" \x01(\tR\x0eauthorityKeyId\x12/\n" +
	"\x13authority_signature\x18\v \x01(\fR\x12authoritySignature\"^\n" +
	"\rWorkspaceData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"G\n" +
	"\x0eWorkspaceClose\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonB.Z,robot-agent/protocols/platform/v1;platformv1b\x06proto3"

var (
	file_platform_v1_workspace_proto_rawDescOnce sync.Once
	file_platform_v1_workspace_proto_rawDescData []byte
)

func file_platform_v1_workspace_proto_rawDescGZIP() []byte {
	file_platform_v1_workspace_proto_rawDescOnce.Do(func() {
		file_platform_v1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_workspace_proto_rawDesc), len(file_platform_v1_workspace_proto_rawDesc)))
	})
	return file_platform_v1_workspace_proto_rawDescData
}

var file_platform_v1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_platform_v1_workspace_proto_goTypes = []any{
	(*TerminalGrant)(nil),  // 0: platform.v1.TerminalGrant
	(*WorkspaceData)(nil),  // 1: platform.v1.WorkspaceData
	(*WorkspaceClose)(nil), // 2: platform.v1.WorkspaceClose
}
var file_platform_v1_workspace_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_platform_v1_workspace_proto_init() }
func file_platform_v1_workspace_proto_init() {
	if File_platform_v1_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_workspace_proto_rawDesc), len(file_platform_v1_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_workspace_proto_goTypes,
		DependencyIndexes: file_platform_v1_workspace_proto_depIdxs,
		MessageInfos:      file_platform_v1_workspace_proto_msgTypes,
	}.Build()
	File_platform_v1_workspace_proto = out.File
	file_platform_v1_workspace_proto_goTypes = nil
	file_platform_v1_workspace_proto_depIdxs = nil
}
